### ISSUE TITLE
Turn on email confirmation in Devise

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#1]
It seems that Avalon uses Devise. We should enable these features if they are not already enabled:
- [ ] email confirmation upon user registration (doesn't seem I needed to confirm during my registration process)
- [ ] password recovery
- [ ] account is lockable so administrator can lock malicious use of accounts

**Comment by taichun** [comment]
Inside /var/www/avalon/config/environments/test.rb this line is blocking
all outgoing emails in the test environment:

  config.action_mailer.delivery_method = :test

Comment it out will allow emails to be sent out.


Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438
