### ISSUE TITLE
Test suite failure: upstream view requirements

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#103]
There are failing view tests that are expecting content related to the upstream avalon on our pages (e.g., the avalon version, link to avalon home page, etc).

The seven failing tests are:

rspec ./spec/features/capybara_homepage_spec.rb:18 # homepage validates presence of header and footer on homepage
rspec ./spec/features/capybara_homepage_spec.rb:49 # checks navigation to external links checks navigation to Avalon Website
rspec ./spec/features/capybara_homepage_spec.rb:55 # checks navigation to external links checks navigation to Contact us page
rspec ./spec/features/capybara_homepage_spec.rb:81 # Sign in page validates presence of items on login page
rspec ./spec/features/capybara_navigation_spec.rb:18 # checks navigation after logging in checks navigation to Browse
rspec ./spec/features/capybara_navigation_spec.rb:72 # Search is able to enter keyword and perform search
rspec ./spec/features/capybara_navigation_spec.rb:78 # Search gives appropriate error when keyword returns no results

A decision needs to be made whether we try to comply with the upstream test requirements, or if we remove/replace these tests.

This issue is a refinement of issue #25.

**Comment by cwant** [comment]
@seanluyk There is at least one decision that needs to be made here (in particular see the bold text below). The test failures are (in English):

* A test expected to find the words "Sample content" on the homepage like it does in stock avalon. I can remove this test;
* A test expected to find a link called "Avalon Media System Project Website" that points to the upstream source website (http://www.avalonmediasystem.org) **(Do we want to add a link to the Avalon project?)**;
* A test expected the 'Contact Us' link to point to a page at path "/comments", but our page is at "/contact" -- I can update this test;
* An error related to signing in. The nature of the issue isn't understood by me yet;
* A test fails because it wasn't expecting there to be two links called 'Browse' on the homepage (menu and footer) -- the test can be fixed to accommodate this;
* A problem with the search box, likely because our search box says "Search ERA A+V" rather than just "Search";
* Same as previous error for the final failure.

**Comment by seanluyk** [comment]
Sure @cwant , we could put a little Avalon logo and link on the page as is done on Indiana's Avalon instance: https://media.dlib.indiana.edu/

**Comment by cwant** [comment]
Hi Sean, would the demo here work? In particular, the little text at the bottom "Powered by Avalon" (like Indiana does).

https://avalon-test.library.ualberta.ca/

Regarding the logo, it might be worth delaying such a decision until Natasha has gone over the look and feel (the logo might disturb the Feng Shui ...). The test suite has no tests that try to determine whether there is a logo on the page or not.

**Comment by seanluyk** [comment]
Looks good to me @cwant. If this satisfies the test I'm happy! Plus, it's probably not worth adding the Avalon logo since its name is changing to a heavy metal band name soon anyway ;)
