### ISSUE TITLE
Avalon 6 upgrade

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#109]
### Descriptive summary

The new Avalon 6 is officially released. Here is a feature list:

--Updated to use current releases of Hydra components
--New installation methods, including official images for Docker
--Preview version of Avalon 5.x to Avalon 6 migration tool (full migration tool release coming soon)
--Full-feature parity with 5.1

We should discuss the upgrade path, actions, and timelines. 

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by cwant** [comment]
Just doing a bit of research, the release page says "Preview version of Avalon 5.x to Avalon 6 migration tool (full migration tool release coming soon)":

https://wiki.dlib.indiana.edu/display/VarVideo/What%27s+New+in+Avalon+6

I guess we could either try out the preview version now, or wait for the full version.

**Comment by weiweishi** [comment]
I will check with them on Slack about the timeline for the full migration
tool. It would make sense if we can migrate current content before launch,
if the timeline works for us. But if not, I'd say hold off testing the
migration until the tool is fully developed.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by cwant** [comment]
Here is the current documentation for the migration:

https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+5.1.6+to+Avalon+6.0

The page says that they will update this shortly after Avalon 6 release.

**Comment by seanluyk** [comment]
This one is done :)
