### ISSUE TITLE
Curate marc relator contributor terms

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/avalon#115]
### Descriptive summary

In order to provide a controlled vocabulary for contributor terms, a curated list of terms needs to be obtained from the full list of marc relators.

### Steps

1. obtain the list of marc relators
2. select candidates based on the following criteria:
conceptually related to media (audio/video)
select a maximum of 50 terms ( @cwant please confirm a number that is suitable to a dropdown)
3. confirm selections with @sfarnel 

### Related work

Broken out from #84

**Comment by zschoenb** [comment]
relator codes (268 count):
https://www.loc.gov/marc/relators/relacode.html

tsv:
http://id.loc.gov/vocabulary/relators.tsv

**Comment by cwant** [comment]
I think 50 should be okay for a pulldown.

**Comment by zschoenb** [comment]
Roles are available at https://github.com/ualbertalib/metadata/blob/master/metadata-wrangling/avalon/contributor_roles.tsv

**Comment by zschoenb** [comment]
This list may be subject to future editing based on UX, service needs, and so forth.

**Comment by seanluyk** [comment]
Looks great @zschoenb, thanks for turning this around so quickly!

**Comment by zschoenb** [comment]
my pleasure :)
