### ISSUE TITLE
Extend language validation to include ISO 639-3

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/avalon#119]
### Descriptive summary

ISO 639-3 (https://raw.githubusercontent.com/datasets/language-codes/master/data/language-codes-full.csv) could be used to validate languages on ingest. ISO639-3 should provide the inclusiveness necessary for many of our multilingual items.

### Expected behavior

Languages such as 'mandarin', 'cantonese', or 'farsi' should validate.

### Actual behavior

Marc language codes are being used to validate languages. This list is not very inclusive. For example, "Chinese" and "Persian" stand-in for the above language identifiers.

**Comment by seanluyk** [comment]
Looks like [this](http://www-01.sil.org/iso639-3/download.asp#LNIndex) is the authoritative version. There's also an explanation of the differences between ISO standards [here](http://www.loc.gov/standards/iso639-2/faq.html#1) FYI.

**Comment by seanluyk** [comment]
P.S. You won't find Cantonese in there - it's classified as Yue, the Mandarin name for Cantonese, which was apparently a controversial choice

**Comment by zschoenb** [comment]
So it seems... Thanks, Sean.

**Comment by zschoenb** [comment]
The mappings also appear to be there.

**Comment by cwant** [comment]
@zschoenb Here is the URL to the current language file (with URIs):

https://github.com/ualbertalib/avalon/blob/master/config/iso639-2.yml

Are there URIs for the 639-3 language set?

**Comment by zschoenb** [comment]
With 639-3, you get multiple language names assigned to the same language code. What do you think the implications are for production?
`
zza:
	:code: zza
	:text: Dimili
	:uri: http://www-01.sil.org/iso639-3/documentation.asp?id=zza
zza:
	:code: zza
	:text: Kirdki
	:uri: http://www-01.sil.org/iso639-3/documentation.asp?id=zza
zza:
	:code: zza
	:text: Zaza
	:uri: http://www-01.sil.org/iso639-3/documentation.asp?id=zza
zza:
	:code: zza
	:text: Zazaki
`

**Comment by seanluyk** [comment]
In the interest of closing this service request, I've had Tai-chun run the batch ingest for this collection with the following language limitations noted:
-Mandarin and Cantonese items both are catalogued as Chinese
-Plautdietsch is catalogued as Low German
-Farsi is catalogued as Persian

I'd like to move this issue to post-launch and we can fix these few items manually after ISO 639-3 is implemented. This is a lower priority for now simply because most collections won't contain items not in ISO 639-2

**Comment by zschoenb** [comment]
That sounds fine. Thanks Sean. I haven't parsed that new language code yet anyway, as per Chris's involvement in the pushmipullyu sprint.

**Comment by seanluyk** [comment]
Doing some cleanup
