### ISSUE TITLE
ERA-AV uses the upstream project's favicon

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#120]
This is the favicon we are currently using:

https://era-av.library.ualberta.ca/favicon.ico

(If you are viewing this on April 5, 2017, you will see an icon with the letter 'a'.)

This is likely a @nnunn task.

**Comment by nnunn** [comment]
This is done in test.

**Comment by cwant** [comment]
The favicon is not present on individual item pages

**Comment by nnunn** [comment]
So I made a new branch, but I don't think I did it right. It's only the last two commits of the the favicons pull request that need to be added...

**Comment by cwant** [comment]
Hi Natasha,

Yeah, the new branch is a bit b0rked. I cherry picked your last two commits to a new branch and submitted a new PR -- you probably got notification.

**Comment by nnunn** [comment]
Great thanks so much!

**Comment by cwant** [comment]
(feel free to review the PR)
