### ISSUE TITLE
Add Z39.50 support (using catalog key) 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#13]
See https://wiki.dlib.indiana.edu/display/VarVideo/Bibliographic+Import+Configuration

**Comment by seanluyk** [comment]
Currently working in test - should be implemented in prod to ensure speedy metadata import for instructional videos

**Comment by seanluyk** [comment]
@weiweishi will talk to @taichun about pushing this change to production

**Comment by seanluyk** [comment]
Bibliographic ID configuration appears to be missing from the resource description form is TEST.

**Comment by cwant** [comment]
One thing to be aware of: when putting in a Bibliographic ID and clicking "Import", the metadata is saved immediately to Fedora, it isn't just loaded into the metadata form. (I had expected that the changes would be committed to Fedora upon clicking save.) A warning should probably be added, either as inline text or as a pop up alert.

**Comment by cwant** [comment]
This one is done, and is in the current release on production.

**Comment by seanluyk** [comment]
Just tested and it looks good to me. Noticed a small issue when dealing with items with no linguistic content (e.g. music). Will create separate issue.
