### ISSUE TITLE
Nosotros collection - captions files not loading

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#133]
### Descriptive Summary
Loading a captions file results in a "we're sorry, but something went wrong" message when the file appears to be [correctly formed](https://en.wikipedia.org/wiki/SubRip). I've tested with some basic files and still get the error.  To see an example of a video with a working captions file go to: https://era-av.library.ualberta.ca/media_objects/avalon:402
-Captions begin at 00:50

Here is the caption text for this video:
1
00:51 --> 00:53
Good evening, friends!

2
00:54 --> 01:00
Nosotros is a show for the entire Spanish-speaking Edmonton community.

In the past, this issue would come up if the file was not formatted properly (including incorrect text encoding - UTF-8 seemed to work best), so it appears that something related to loading caption files is broken.

This is marked high priority as transcriptions of two videos were done as a class assignment and are waiting to be loaded.

**Comment by cwant** [comment]
Hi @seanluyk,

So your workflow when you get the error is:

* Upload the movie file;
* Go to the Structure page and click the plus for captions.
* Select a captions file and press upload, then the error happens.

Is that correct?

Do you have a valid captions file I can test with?

**Comment by seanluyk** [comment]
That's correct, @cwant 
I'm attaching the captions file that worked with [this video](https://era-av.library.ualberta.ca/media_objects/avalon:402) back in September:
>[Nosotros_Subtitling.srt.txt](https://github.com/ualbertalib/avalon/files/968930/Nosotros_Subtitling.srt.txt)

I see some issues with the new files (missing some spaces between the arrows, which I will request to have fixed), but here they are FYI:

For [this one](https://era-av.library.ualberta.ca/media_objects/avalon:316)
>[ProgramaNosotros67.txt](https://github.com/ualbertalib/avalon/files/968935/ProgramaNosotros67.txt)

And [this one](https://era-av.library.ualberta.ca/media_objects/avalon:392)
>[ProgramaNosotros66.txt](https://github.com/ualbertalib/avalon/files/968939/ProgramaNosotros66.txt)

**Comment by cwant** [comment]
I did not get a crash when I uploaded the ProgramaNosotros67.txt captions to a movie in my dev instance. That said, the captions did not show up though when I played the movie though!

When I put the spaces in around the arrows in the file, the captions showed up, so I think that might be what's causing the problem.

Below is the file with the fixed arrows, if you care to try on the real video:

[ProgramaNosotros67-2.txt](https://github.com/ualbertalib/avalon/files/970892/ProgramaNosotros67-2.txt)

**Comment by seanluyk** [comment]
Thanks for investigating, @cwant. Unfortunately, I'm getting the same error when I try to upload this file in production.

**Comment by cwant** [comment]
Hi Sean,

Do you have a link to the source video? I can try to ingest it in the test stack and see if I hit the same error. Unfortunately, I don't have have access to the production logs (perhaps @taichun can take a look to see if there is any more information there).

Chris

**Comment by seanluyk** [comment]
That caption file should go with this one: https://era-av.library.ualberta.ca/media_objects/avalon:316

Good idea, hopefully, a log would provide more information. The really weird part is that even if I make a small basic file with no mistakes, it still won't load.

**Comment by cwant** [comment]
This is interesting, I get the same failure in production, but not in dev or test.
I think this is either a problem with the firewall or with the permissions. Something I've noticed: when I log into production avalon as the admin user, I can not create new items in Sandbox or in Nosotros (the rails application crashes). @seanluyk , can you confirm that the same thing happens to you?

**Comment by seanluyk** [comment]
Good catch @cwant  - I experience the same issue in both of those collections and ALL collections for that matter. Looks like something on the infrastructure side is going on, flagging @taichun

**Comment by taichun** [comment]
These two collections exist before we have Avalon version updates to the
current 5.1.x branch which means their Fedora store are ... old? I suspect
this issue is related to either Fedora or Solr data associated with these
two collections.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by cwant** [comment]
@taichun  I just tried creating a new collection with the admin account and got an error.

**Comment by taichun** [comment]
Ok, seems like Fedora is the culprit and I'm currently troubleshooting
this. Don't do anything on the collections yet.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by taichun** [comment]
It seems that the recent java VM update is what causing the Fedora error.
I've since restarted the service and can attach the caption file to the
video with success.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by seanluyk** [comment]
Wonderful, thanks @taichun  - I was able to add the file to the other video. I think it's safe to close this issue.

**Comment by cwant** [comment]
@taichun Do you know the root of the issue on the VM? Also, what was done to correct the issue?

**Comment by taichun** [comment]
The root issue is the java package was updated recently but the tomcat
service still running from 20 days ago so it tries to local some files from
the previous package but failed. I would think a service restart after each
package update would mitigate the issue, or a daily reboot/service restart.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by taichun** [comment]
I'm still debating which way to tackle this.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438
