### ISSUE TITLE
Error: Nilclass on file conversion process

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#14]
Attempted to upload [mp4 video](https://era-av.library.ualberta.ca/media_objects/avalon:154) and received the following conversion error:

![image](https://cloud.githubusercontent.com/assets/14880206/16967160/ffe8a43c-4dc4-11e6-81f2-91696d719343.png)

**Comment by dpd123** [comment]
Filesystem problem on Matterhorn server was fixed.
