### ISSUE TITLE
TravisCI Test Flapping

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#146]
### Sometimes tests pass in Travis, other times they don't

"If the Travis build fails, just run it again and maybe it will pass"

The above statement describes the current CI workflow for Avalon. This situation erodes confidence in the test suite.

**Comment by cwant** [comment]
It may be worth downloading the docker image that travis uses and see if the tests a flaky when run locally:

https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

**Comment by cwant** [comment]
As an experiment, I've configured Travis to use Ubuntu 14.04 instead of 12.04 to see if there is a difference:

https://github.com/ualbertalib/avalon/tree/cwant/issue_146_travis_test_flapping

Conclusion: no difference, the tests are still flaky.

**Comment by jefferya** [comment]
@weiweishi. Occurs occasionally. Anecdotal experience, mid to late afternoon intermittently. My brief troubleshooting seemed to point toward the data for the test intermittent not being fully written/stored in part of the stack (e.g., Solr/Fedora/DB) before the test is executed.   

My opinion, close and if the flapping becomes an issue then invest time.
