### ISSUE TITLE
Login from eClass may allow email alias

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#15]
When a user logs in from an eClass, ERA A+V authenticates the user based on the profile email address attached with the eClass and not the user's CCID.

A possible solution is to merge multiple accounts using information from IST through shibboleth, LDAP or something similar.

**Comment by cwant** [comment]
@umarqasim please elaborate a bit more.

**Comment by umarqasim** [comment]
When I login to eClass and then click an LTI link to access an item in ERA A+V, the system considers me as a different person than when I directly login to ERA A+V even though the login id appears same at the upper right corner. May be @weiweishi can confirm but I think David added some code to append @alberta.ca when someone logins to ERA A+V in order to avoid some identity issues we were having at that time. This may be causing the system to think mqasim and mqasim@ualberta.ca as two separate users.

**Comment by cwant** [comment]
Hi Umar,

Poking around a bit, it looks like Avalon doesn't treat you as a different person, but it downgrades your permissions when logging in using LTI -- it doesn't do a "full login". Making Avalon do a full login when coming in from LTI is a one-line change.

There are times when doing a full login would be a disadvantage. Suppose you are testing what a person from an eClass can see on Avalon. If LTI does a full login, then you get your full basket of permissions that come with your elevated status on avalon, so you might assume that an eClass feature is working for you, but it doesn't actually work for the eClass visitors. Something to consider ...

Chris

**Comment by umarqasim** [comment]
It this is the case, then leaving it as is probably is a better option. I was worried the system may be treating the same user differently and could cause other ambiguities but if it is intentional, makes sense to let it work as designed.

**Comment by umarqasim** [comment]
This is a feature not a bug, closing ticket.
