### ISSUE TITLE
Invalid MasterFiles in production stack

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#154]
1641 master files have the following errors:

  Workflow name field is required.
  Workflow name is not included in the list

These should either be corrected, or the validation should be relaxed. This was perhaps caused by a Matterhorn issue (?).

**Comment by cwant** [comment]
Some discoveries: all of these perverse Master Files were created between May 12-15 this year.

A mostly solid range of object id's between avalon:1641 - avalon:3306, in particular:

1641 - 1790
1794
1798 - 1801
1805 - 1807
1811 - 1820
1824 -1862
1866 - 1873
1877 - 2031
2033 - 3306

I'm not sure what was going on that day ... .

**Comment by cwant** [comment]
There is an email about the new encoding server on May 12th, that might have put things in a wacky state for a couple of days. But from the emails, I don't think it was put into production until May 18th ... so probably a red herring.

**Comment by seanluyk** [comment]
Weird...just tried to see if they were from a particular deposit and none of these objects appear to be real (they point to a something's gone wrong error)

**Comment by cwant** [comment]
Yeah, I am only able to see them in Fedora, e.g.:

http://era-av.library.ualberta.ca:8080/fedora/objects/avalon:3306

(You likely need to delete HSTS for domain era-av.library.ualberta.ca in your browser to see this link correctly -- I can help with that if it's not easy for you.)

This is where I was able to see the creation dates of the objects.

**Comment by seanluyk** [comment]
Thanks, @cwant, luckily I was able to figure this out from some Googling. Still very strange - I wonder if these are created from failed batch ingests?

**Comment by cwant** [comment]
Hi Sean,

I noticed that on May 11th I have a message from you with subject line "Fwd: Failed batch ingest processing errors for: UAL Avalon test batch".

It's possible that some of the problems you had with file naming triggered some issues (or that some of the problems you were having were symptoms of other issues in the stack).

**Comment by seanluyk** [comment]
That could be it, @cwant. You would think that objects wouldn't be created if there were errors, but I'm not entirely sure in which order the process goes.

**Comment by cwant** [comment]
All of the invalid MasterFiles have been cleaned out. This was done with a script that looked like:

```ruby
PIDS=['avalon:1641','avalon:1642' ... <snip>...]
raise "Unexpected count!" unless PIDS.count == 1641

PIDS.each do |pid|
  mf = MasterFile.find(pid)
  raise "#{pid} is valid!!!" if mf.valid?
  raise "#{pid} has a MediaObject!!!" if mf.mediaobject_id
  raise "#{pid} has a file location!!!" if mf.file_location
  raise "#{pid} has a checksum!!!" if mf.file_checksum
  raise "#{pid} has a workflow id!!!" if mf.workflow_id
  raise "#{pid} has a workflow name!!!" if mf.workflow_name

  puts "Deleting #{pid}"
  mf.destroy
end
```

Closing ticket.
