### ISSUE TITLE
Mobile: Various small Responsive UI papercuts

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/avalon#16]
I found a few small issues with the UI during the load testing today, all related to the responsive layout when resizing the browser to match mobile resolutions:
- [ ] https://era-av.library.ualberta.ca -- feature collections are inconsistently sized below 1000px in width
- [ ] Below ~760px in width:
  - [ ] On any page, the header colour background changes from grey to white
  - [ ] The University Libraries logo is truncated awkwardly
  - [ ] An Avalon Media System logo pops in on the nav bar. (Possibly intentional, but I'm mentioning it in case it conflicts with our branding).
  - [ ] The search box disappears and there is no way to access it.
  - [ ] The Footer loses the "Policies" and "Quick Links" sections (possibly intentional, in which case disregard this)

**Comment by umarqasim** [comment]
May get resolved in the new 5.1.4 release #20

**Comment by nnunn** [comment]
done in test.
