### ISSUE TITLE
using rails helper/form_tag

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#167]
Should be using the rails html helpers as much as possible. So here use form_tag, to avoid CSRF attacks and other things: 
https://github.com/ualbertalib/avalon/blob/808852c7d7a5cad9fbbc3d5dab8df221dac6f8f1/app/views/modules/_header.html.erb#L39

**Comment by nnunn** [comment]
I have made this change within _header.html.erb and home.html.erb. However, I'm not sure if there are other places where we should be replacing forms with the form_tag.

**Comment by cwant** [comment]
The particular reference you point to is fixed in the current PR. Closing.
