### ISSUE TITLE
Remove Unit in the browse facets

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#17]
Remove unit in the browse facets.

**Comment by seanluyk** [comment]
This needs more discussion in light of the possibility that unit is related to access controls

**Comment by cwant** [comment]
Okay, this is a one-line change (just comment out the line that declares 'unit' as a facet).
I can leave it out for this sprint until it is discussed further, if you prefer.

**Comment by seanluyk** [comment]
Hmmm...now that I do some more digging I've found out that "a collection's unit is just a label: there are no privileges associated with units."  @cwant please proceed with this change and we can always revisit if we find out it's useful
