### ISSUE TITLE
Health monitoring for Delayed Job

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#174]
@taichun brought up at standup this morning the issues we have had with delayed job (it sometimes stalls, causing things like ingest and batch ingest button to fail). We need to set up some form of health monitoring for this.

I would like to propose a daily cron task that runs at night and does:

* runs the code in "rake dedelayed_job:status"
* if that shows issues, run the code in "rake delayed_job:start"
* if that doesn't improve things, send a report to rollbar.

@taichun: does this sound reasonable?

**Comment by umarqasim** [comment]
Another option is to show the status of delayed_job somewhere on the admin interface and allow administrators to restart it from the interface if the service is down.

**Comment by seanluyk** [comment]
Doing some cleanup
