### ISSUE TITLE
[SPIKE] Investigate migration tool for migrating to Avalon 6

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/avalon#181]
### Descriptive summary

Following the release of the Avalon 5.x to 6.x migration tool and the impending migration of ERA A+V to Avalon, we should investigate the effectiveness of the tool and begin plans for a migration workflow. A google docs report will outline options for migration, including a report on the existing migration tool. See [the migration tool](https://github.com/avalonmediasystem/avalon/releases/tag/v6.1.0) for more info.

**Comment by seanluyk** [comment]
Doing some cleanup
