### ISSUE TITLE
Player showing Nan:Nan instead of time

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#19]
when running a video, the player stopped working and displayed Nan:Nan where it displays the current running time

**Comment by seanluyk** [comment]
Was just able to successfully replicate this issue while testing playback on my laptop on a wireless connection - I think this comes up when the server is being rebooted during playback, which lines up with when I was viewing the video.

**Comment by seanluyk** [comment]
Can't replicate, closing
