### ISSUE TITLE
Flash plugin blocking peculiarity

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#225]
### Descriptive summary
I've come across a peculiar issue with Flash plugin blocking in Chrome. I've added http://[*.]era-av.library.ualberta.ca to the hosts allowed to run Flash without asking. Once this is set, Flash does run for videos without asking, but not for audio without asking (plugin must be run every time from the browser bar for audio files). 

### Expected behavior
Once era-av has been added to the hosts able to run Flash without permission, both audio and video players will appear/play without asking

### Steps to reproduce the behavior
1. Add ERA A+V to lists of hosts able to run Flash w/o asking in Chrome
1. Compare browser behavior of [audio recording](https://era-av.library.ualberta.ca/media_objects/avalon:3785) to [video recording](https://era-av.library.ualberta.ca/media_objects/avalon:1229) 

### Related work
#223

**Comment by cwant** [comment]
Definitely a tricky one. Upstream Avalon has the same problem obviously, and they've basically given up on fixing it for now. Some dialog on their issue here:

https://github.com/avalonmediasystem/avalon/issues/1948#issuecomment-321277441

**Comment by seanluyk** [comment]
One possible interim solution is to link the IU and/or Avalon page with instructions

**Comment by cwant** [comment]
Also, will run an Avalon 6.1 docker container and see if the same behavior exists.

**Comment by cwant** [comment]
It looks to me that whatever is causing the issue with the audio content is not present in Avalon 6.1. Compare the behavior of the same audio file:

https://era-av.library.ualberta.ca/media_objects/avalon:3990 (ours)
http://206.167.181.135:3000/media_objects/m613mx59x (Avalon 6.1)

The Avalon 6.1 asks about permitting Flash, but does not have the strange forced plugin-blocking behaviour.

**Comment by seanluyk** [comment]
Thanks, @cwant for investigating. I can confirm that I am not experiencing the issue in Avalon 6.1. Yet another reason for us to upgrade! I've added the phase 2 label.

**Comment by umarqasim** [comment]
@cwant Thanks for investigating this, looks fine with the upgrade and the issue will be resolved in the phase 2. However, can you work on displaying a message for now something as simple as 

"Unable to see an audio player? "
"check your browser settings as your adobe flash player plugin may be blocked"

**Comment by seanluyk** [comment]
@cwant @umarqasim or alternatively, link to the really detailed wikipage at Indiana

**Comment by cwant** [comment]
I have a pull request issued that upgrades some of our mediaelement code from upstream avalon. This seems to fix the "audio always blocked on chrome" issue.

**Comment by seanluyk** [comment]
This looks great with the exception of a minor style issue. The first section of a multi-item object's title is wrapped into the error message
![image](https://user-images.githubusercontent.com/14880206/31087453-509fef76-a75a-11e7-91d0-deb7bdc2ec6e.png)

**Comment by seanluyk** [comment]
Doing some cleanup
