### ISSUE TITLE
Video Player with Black Screen 

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#241]
### Descriptive summary
When a video is run using the play button available in the centre of the video player screen, the whole screen goes black and remains black. The video continues to run with sound. I also noticed that sometimes the video only plays on a half a screen while other space is black.

### Expected behavior
The screen should not go black and run properly when run from any play button.

### Actual behavior
This may be related to "mouse over/hover over" script  we  are using for other purposes

### Steps to reproduce the behavior

1. Open a video page
2. Play the video using the centre play button within the player

**Comment by cwant** [comment]
Based on testing, here are discoveries:

* So far, can only replicate on Umar's Windows machine running firefox (chrome does not exhibit this behaviour).
* On DI Consult room Windows machine, can't replicate using firefox

Does not appear to happen on Linux. Safari on Mac shows some problems (but not the problem described here), which should be covered by a separate ticket.

**Comment by seanluyk** [comment]
Doing some cleanup
