### ISSUE TITLE
Logging for SOCAN

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#248]
Placeholder ticket for investigating and scoping out requirements for stream/item access to report to SOCAN.

Notes:

* Wowza logging information here, in logging section: http://www.wowza.com/resources/WowzaMediaServer_UsersGuide.pdf

**Comment by cwant** [comment]
Just a note about adding custom information to the stream URL for Wowza logging purposes. If we want to do this, here is the place to do it:

https://github.com/ualbertalib/avalon/blob/master/app/assets/javascripts/avalon_player.js.coffee#L72

**Comment by cwant** [comment]
An initial experiment to get logging information for SOCAN into the wowza log is here:

https://github.com/ualbertalib/avalon/tree/cwant/socan_logging

**Comment by seanluyk** [comment]
Doing some cleanup
