### ISSUE TITLE
Static warning page about Chrome/Flash

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#249]
As per Umar's message. Content here:

https://docs.google.com/document/d/16JWvw3Oqcp9286QmRIsA4mZb5YZIERyEJXM7SqRDnOU/edit

**Comment by cwant** [comment]
@umarqasim @seanluyk I have reworked the flash error messages coming from ERA-AV, so I'll need to redo the screenshots on the new help page. Would you like any modifications from what you see below before I make the screenshots?

* eClass:
![flash-error-eclass](https://user-images.githubusercontent.com/672104/30936074-eba0b858-a38f-11e7-8ecb-e16bd14ac733.png)
* ERA-AV
![flash-error-era-av](https://user-images.githubusercontent.com/672104/30936106-0abfeb96-a390-11e7-9979-801464fef974.png)

**Comment by umarqasim** [comment]
@seanluyk 

What if we make the last two statements something like

"To enable flash in your browser, please see our help page"

"You can also check Adobe Flash Player Help page for more information"

**Comment by seanluyk** [comment]
@umarqasim sounds good to me - although this mostly refers to Chrome, users may need assistance installing/enabling Flash in Safari and Firefox too

**Comment by umarqasim** [comment]
@seanluyk I was thinking more in terms of having a local help page covering major browsers. We do have links for a couple of other browsers at the bottom but I think you are right may be we just stick to resolving the chrome issue and refere the Adobe page for other browsers

@cwant please go with what you have suggested.

**Comment by seanluyk** [comment]
Looks great to me, @cwant
