### ISSUE TITLE
Setting up Dev environment for Avalon

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#26]
- [ ] Chris to work with Tai-chun to figure out the details of this dev instance.
- [ ] Work with Tricia to get details about ansible enviornment

**Comment by weiweishi** [comment]
- [ ] the ansible playbook separate the Rails test/staging environments

**Comment by weiweishi** [comment]
- [ ] a test run to verify the branch on ansible-config (fedora and solr configurations) works to set up a dev environment.

**Comment by cwant** [comment]
Done. See changes to ansible playbook and avalon docker work.
