### ISSUE TITLE
Avalon 6: Rework License/Access rights

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#294]
PR #341 
See description of work in comment below.

**Comment by cwant** [comment]
A meeting has been scheduled for June 21 to discuss this.

**Comment by cwant** [comment]
Decision from the meeting:

We will consolidate the licensing to use one field in the MODS document (Terms of Use, a.k.a the `accessCondition` XML nodes with attribute `type` set to `use and reproduction`). This matches the field used in upstream Avalon. This field will now be required.

We will discontinue (and migrate existing data from) the use of `accessCondition` XML nodes with attribute `type` set to `license` and `rights` (this is the current practice for the required licensing fields we use in Avalon 5).

The values stored in the terms of use field will have one of two forms:

* either a URI from controlled vocabulary (e.g., `http://creativecommons.org/licenses/by-nc-nd/4.0/`), or;
* free form text.

The user interface will figure out how to handle each. There will be a pulldown for stock licenses with final one 'Enter your own license terms ...'. This last choice will bring up text area for custom text, otherwise a URI is inserted into the metadata. The user interface will never show the actual URI, but will instead show a human friendly version (e.g., `https://creativecommons.org/licenses/by/4.0/` shows up as `Attribution 4.0 International`). Batch ingest will take a URI or free form test. There will be a sanity check for misspelled URIs (e.g., if the terms of use field starts with 'http' but isn't from the controlled vocabulary, mark as an error).

This field will be labelled "Terms of Use / License" in the user interface.

@umarqasim @anayram hopefully this matches your understanding from the meeting.
@weiweishi @seanluyk @sfarnel  You might want to take a quick look over this.

**Comment by umarqasim** [comment]
Yes, this exactly is my understanding how we will be handling this.

**Comment by sfarnel** [comment]
Thanks @cwant and all! I think this looks excellent.

**Comment by seanluyk** [comment]
Sounds great, @cwant!

*Sean Luyk <https://sites.google.com/a/ualberta.ca/sean-luyk/> *[lʌʊ̈k
<https://en.wikipedia.org/wiki/File:Nl-Luik.ogg>]*, MA, MLIS*
Digital Initiatives Projects Librarian
780-492-6779

**Comment by anayram** [comment]
This is great, thanks, @cwant !
