### ISSUE TITLE
adding a unit option not available

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#3]
in the current interface, admin is unable to add new units. Only one default unit available for all collections.

**Comment by seanluyk** [comment]
I see two possible solutions to this issue:

1. @umarqasim and I provide Chris with a list of Units, which must be added to avalon/config/controlled_vocabulary.yml.  as per https://wiki.dlib.indiana.edu/display/VarVideo/Managing+Controlled+Vocabularies

2. Decide to not use multiple units, but rename "Default Unit" to something less generic (e.g. University of Alberta)

Any preferences @umarqasim?

**Comment by umarqasim** [comment]
I know we talked about this in the past. On the [IU Avalon repository website](https://media.dlib.indiana.edu/), I feel it is confusing to have similar names for collections and units. [Northwestern](https://media.northwestern.edu/) on the other hand is managing it better. How we will differentiate between these two categories is important and if we are not able to make that difference clear, I prefer to just use one unit ("University of Alberta" seems a good option)

**Comment by seanluyk** [comment]
Agreed - let's plan to rename Default Unit to University of Alberta OR University of Alberta Libraries

**Comment by seanluyk** [comment]
Related to #17 and #12. Once we have consensus on what to name the Default Unit, the references issues can be worked through.

**Comment by seanluyk** [comment]
Taken care of in #17 closing
