### ISSUE TITLE
Create a page on the libraries website for service details

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#30]
Need to work on a page with details about ERA A+V service details, what can be deposited. This page can go on the DI site or the libraries website. 

May be solved in #44

**Comment by seanluyk** [comment]
@nnunn here is my proposed content for the ERA A+V services page(s) can be accessed [here](https://docs.google.com/a/ualberta.ca/document/d/1zQ_wzt8yCodahskDcjSQGI1TwDc-_20vHF2OOY5LQ98/edit?usp=sharing). As this is not ERA A+V specific please let me know if I need to put in a helpdesk ticket, contact WAT, etc.

@leahvanderjagt and @sfbetz - if you have a chance, please add your questions and comments. This is short and sweet as decided at a previous meeting.

**Comment by nnunn** [comment]
This is ready to go, and will be done once we are ready to "launch".
