### ISSUE TITLE
Make related item links open in new window instead of same window

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#32]
For example,  https://era-av.library.ualberta.ca/media_objects/avalon:797

Ideally, all related item links should open in a new window/tab so playback isn't interrupted by mistake.

**Comment by cwant** [comment]
This issue isn't included in the current sprint, but I've worked out a solution that is being demoed on the test server.

**Comment by cwant** [comment]
Upstream pull request created for the patch demoed:

https://github.com/avalonmediasystem/avalon/pull/1554

**Comment by seanluyk** [comment]
This is great, thanks, Chris!

**Comment by cwant** [comment]
Deployed in release 5.1.5.20170201.uofa. Closing ticket.
