### ISSUE TITLE
License in batch ingests

### ISSUE THREAD

**Issue by alexmmcphail** [ualbertalib/avalon#332]
### Descriptive summary

The default spreadsheet for batch ingest does not include a column for inputting license information. A batch ingest can be validated and processed completely without this information, but editing the item through the browser will require license information to be inputted.

### Fix

Add a column into the spreadsheet with the header `access_restrictions_license`.
You can either input a custom license text, or one of the predefined licenses:
```
Attribution_4.0_International
Attribution-ShareAlike_4.0_International
Attribution-NonCommercial_4.0_International
Attribution_NoDerivs_4.0_International
Attribution-NonCommercial-ShareAlike_4.0_International
Public_Domain_Mark_1.0
CC0_1.0_Universal
```
Using the text `User_Defined_Rights_Statement` will return an error unless a column with the header `license_type` is created and filled out. Custom license text can be inputted in this column - although this is redundant since the `access_restrictions_license` column already does that. 

### Expected behavior

Custom text through the described method should appear the same as custom text added via the edit dialogue in the browser.

Ideally, the custom text should appear in the object's main page and the editing dialogue.

### Actual behavior

Custom text through the batch ingest will be visible on the object's main page, while entering custom text through the browser dialogue simply displays "User_Defined_Rights_Statement". 

When editing an object that has custom license text from a batch ingest, the license field will appear empty. This custom text can not be edited or viewed through the editing dialogue. If you are to select "Enter your own license terms..." under "Choose A License", "User_Defined_Rights_Statement" will appear on the object's main page rather than the custom text.

See screenshots in next section.

### Steps to reproduce the behavior

1. Create a batch ingest as per https://wiki.dlib.indiana.edu/display/VarVideo/Uploading+Content+using+Batch+Ingest
2. In sheet 1 of the spreadsheet, add a column with `access_restrictions_license` in row 2 and insert license text underneath.
![license text through batch ingest](https://user-images.githubusercontent.com/40805235/42241001-59bc0fd8-7ec6-11e8-8f69-3c8c62bd93a4.png)

To observe behaviour when editing through the browser
1. Select Edit
2. Select Resource description
3. Under "Choose a license:" select "Enter your own license terms..."
4. Fill out "Custom license text"
5. Save your edit and return to the object's main page.
![license text edit dialogue](https://user-images.githubusercontent.com/40805235/42241006-5e87b454-7ec6-11e8-908f-76de92944632.png)

For examples of objects with various methods of entering licenses, please see the Sandbox category in ERA A/V: https://era-av.library.ualberta.ca/catalog?f%5Bcollection_ssim%5D%5B%5D=Sandbox

@sfarnel @seanluyk @weiweishi @umarqasim @cwant @anayram

**Comment by anayram** [comment]
Thank you for the detailed summary @alexmmcphail !

**Comment by umarqasim** [comment]
Thanks, Alex!

*--*
*Umar Qasim, PhD*
Digital Preservation Officer
2-10N Cameron Library | University of Alberta
Edmonton, Alberta T6G 2J8, Canada
Tel: 780-492-9861 | Fax: 780-492-9243
umar.qasim@ualberta.ca | http://www.umarqasim.ca

**Comment by anayram** [comment]
This has been resolved with the transition to Avalon 6 and migration cleanup.
