### ISSUE TITLE
Avalon-6: Batch Ingest Button

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#336]
Port over the Batch Ingest Button from Avalon 5.

Previous work: #56

**Comment by weiweishi** [comment]
Batch ingest workflow differences in Avalon 6 compared to Avalon 5:
- It will remove the manifest file after the ingest process is completed
- Push the metadata validation to the background job, but the message indicating metadata validation was already completed successfully. 
- New cron jobs available.

**Comment by cwant** [comment]
As per the decision made in #343, the batch ingest button is no longer needed (batches get ingested as soon as the manifest is uploaded via cron, and don't need a button to ingest).

**Comment by cwant** [comment]
Unless the discussion above needs comment, will close this issue.
