### ISSUE TITLE
Upgrade to version 6.4.3

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#344]
A heads up From Chris Colvard on the Avalon Slack:

> @cwant FYI we’re working on a 6.4.3 bugfix release that should land really soon.
> https://github.com/avalonmediasystem/avalon/pull/2985

This will be a bugfix release. In particular, it has a fix of a bug I am hitting right now (all batch ingest status emails get broken if there is a batch with deleted objects in it).

Might be worth merging after it's released. Another option is to just cherry-pick the things we need.

**Comment by seanluyk** [comment]
@pbinkley @cwant Yes, please go ahead!
