### ISSUE TITLE
Bottom Quicklinks Menu Color theme

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#35]
The bottom Quicklinks Menu colour scheme needs to be changed. Visited item colour is too dim and should be changed to a more contrasting colour for better readability.

**Comment by seanluyk** [comment]
Added this to #23 closing

**Comment by cwant** [comment]
The main issue here is that the visited link colour is the same for the entire site, whether the background is light or dark. We may need to distinguish between the two scenarios in the stylesheets.

Attached is a before and after with a new colour for visited links (Before: hex 2a5459, After: hex 3a7479).

![quick_links_before_after](https://cloud.githubusercontent.com/assets/672104/22761572/8d814274-ee18-11e6-94d4-080298c7da2e.png)

Is this pronounced enough, or should it go further?

**Comment by seanluyk** [comment]
This looks better @cwant, thanks.
