### ISSUE TITLE
Avalon 6: Remove bibliographic import

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#373]
Basically removing the field from the form.

**Comment by jefferya** [comment]
Action item:
* remove `Bibliographic ID` block from the `Resource description` form

Reasoning (from Chris Want via Slack):
* Putting something in that form field and pressing import grabs data from the Z39.50 server and clobbers the existing data (and not just in the form too -- it commits it to disk!)
* It's a dangerous feature we don't use so we're getting rid of it (the safer alternative is to let metadata people assemble the import data and batch ingest it)
