### ISSUE TITLE
Avalon 6: static pages

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#375]
Previous work:  1ce628a

Note: Avalon has an 'about page' gem that has some nifty health check features. Might be worth preserving that (currently set to mount on '/about').

**Comment by pbinkley** [comment]
@umarqasim could you make a list of the changes that are needed to satisfy the requirement to minimally brand the default Avalon 6 look? E.g. make a screenshot and provide notes "put this U of A log here", "Change this background colour to this shade of green", etc.? With that kind of detail we can move ahead and finish the changes.

**Comment by pbinkley** [comment]
This one needs details of scope. Is it just the health check features that we are doing? @umarqasim

**Comment by umarqasim** [comment]
Chris suggested to use this "about page" gem in Avalon. As I recall it was a sprint to see how to configure/use this gem and there is no development effort required. There is no urgency to implement this gem and we can look at it after the launch.
