### ISSUE TITLE
Avalon 6 doesn't seem to send the "It's all done" email after batch ingest

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#397]
After the item is ingested, and after running `bundle exec rake avalon:batch:ingest_status_check`, the `BatchRegistries` entry for the batch has `completed_email_sent` set to true (can see the email in the log that says that the metadata passed validation), but has `processed_email_sent` set to false (no email sent saying that the files were encoded)

**Comment by cwant** [comment]
This is a bit of a mess.

The batch ingest process seems to be oblivious to the encoding process after metadata has been validated.

I've done a contrived example where encoding fails, but the system creates a `MediaObject` with metadata but no media (`MasterFile`). This is problematic, since the `MasterFile` is usually the thing that tells you about the encoding process.

**Comment by seanluyk** [comment]
Fixed in 6 upgrade. Closing.
