### ISSUE TITLE
[Avalon] Migration test

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/avalon#408]
Run the out-of-the-box migration rake task in the UAT environment, from the Avalon 5 Fedora instance on colburn (populated with a snapshot of production data) to the Avalon 6 instance. This will then allow @anayram to inspect the results and determine what work is needed (if any) to enable a production migration.

**Comment by anayram** [comment]
Thanks @pbinkley

**Comment by jefferya** [comment]
Instructions:
https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+5.1.6+to+Avalon+6.0

Note: resource index must be enabled on Fedora 3 for the migration script to execute (i.e., resource index leveraged to build a set of Pids).

**Comment by jefferya** [comment]
Instruction: 
https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+5.1.6+to+Avalon+6.0

```
docker-compose exec avalon bash
RAIL_ENV=development bundle exec rake avalon:wipeout CONFIRM=yes
apt update
apt install mysql-client
RAIL_ENV=development bundle exec rails dbconsole
source avalon.r5.dump.sql
RAIL_ENV=development bundle exec rake avalon:migrate:repo CONFIRM=yes
```

**Comment by jefferya** [comment]
@pbinkley @weiweishi 

This link should work for migrating content for `avalon6-test`:

<https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+5.1.6+to+Avalon+6.0>

Unknowns (see wiki link above for details):
- need environment variables to be accessible via the bundle exec command
- need read access to the Avalon 5 Fedora
- need a db dump from Avalon 5

The Oct. 4, 2018 comment is for a Docker container but may contain some tips that continue to be applicable, more specifically:

-  `export parallel_processes=1`: might need to be set if spurious errors occur (e.g., missing collection object) during the migration (assumptions during the Oct. 4th, 2018 test was that Fedora write operations didn't always complete fast enough to fulfil a read leading to Collection, MediaObject, and MasterFile object linking issues)

**Comment by jefferya** [comment]
WIP: recording test env commands

```
set -a && . /etc/sysconfig/avalon6_env && set +a

RAILS_ENV=staging FEDORA_BASE_PATH=staging bundle exec rake db:migrate
RAILS_ENV=staging FEDORA_BASE_PATH=staging bundle exec rake avalon:wipeout CONFIRM=yes

RAILS_ENV=staging FEDORA_BASE_PATH=staging bundle exec rails dbconsole
RAILS_ENV=staging FEDORA_BASE_PATH=staging bundle exec rake avalon:migrate:repo CONFIRM=yes
```

**Comment by jefferya** [comment]
Need to update derivative streaming base url:
`bundle exec rake avalon:derivative:set_streams`

**Comment by jefferya** [comment]
If terms of use validation needs to be disabled see this branch:
https://github.com/ualbertalib/avalon/tree/feature/disable_terms_of_use_migration
