### ISSUE TITLE
Batch ingest - Gaudun-Lakusta Family Collection

### ISSUE THREAD

**Issue by anayram** [ualbertalib/avalon#420]
**Brief description of the batch**
Batch ingest for Gaudun-Lakusta Family Collection, Kule Folklore Centre

**Collection Title:**
Gaudun-Lakusta Family Collection

**Collection Description:**
The collection consists of audio and video recordings about life of two Ukrainian Canadian families: Nick and Stephanie Gaudun and John and Raifta Lakusta, including immigration to Canada from East-Central Europe, first years of settlement, finding a job, starting a business, finding a spouse, growing a family.

**Manifest**
https://docs.google.com/spreadsheets/d/1wDIFQIu0BTAyB3_W8ZKHibNQJBxymtqrtx_POq8E3eo/edit?usp=sharing

**Batch files**
To be shared by researcher.

**Comment by anayram** [comment]
Batch files available from
https://drive.google.com/drive/folders/1YP-dZq_T81RqiFSfKjkNAKynbPZABCNr?usp=sharing
(link open to specific users only)

**Comment by kgrant1** [comment]
**Batch ingest successfully completed on 02/22/2019** 
_Note: The objects are currently finishing the conversion process._

**Batch ID:** 
5019

**Collection Link:**
https://era-av.library.ualberta.ca/catalog?_=1550864939216&f%5Bcollection_ssim%5D%5B%5D=Gaudun-Lakusta+Family+Collection&q=&search_field=all_fields

**Comment by anayram** [comment]
Thanks very much, @kgrant1 

Just as we did for this ticket, let's continue to keep track of
1. Manifest files location
2. Original media files location (when applicable)
3. Batch ingest id
4. Collection link for reference
5. Date batch was completed (optional)

Closing this item. Metadata has been checked and researcher has been notified.
