### ISSUE TITLE
Batch Ingest - Just Powers Collection

### ISSUE THREAD

**Issue by anayram** [ualbertalib/avalon#421]
**Brief description of batch**
From description by research assistants:
> Just Powers (JP) team outsourced the transcription of the (more or less) raw recordings of all interviews and talks recorded for the iDoc sub-project. Hired RAs then edited the transcripts for accuracy and highlighted important sections, which were then used to create short 60-second video clips, and also categorized each interview according to a number of subject-keywords related to the project that will be used to categorize media on the JP website.

> Two potential archival projects are coming out of the JP project—one related to the logistics of the iDoc archive (public facing through our website and hosted/archived through ERA) and other multimedia created by the JP team (including podcasts), and one related to a documentation of activist online activity and/or cultural production. The latter is on hold while we begin the foundational stages of archiving the iDoc videos/JP podcasts through ERA while also providing public access to streaming videos. We will also be captioning the videos using the transcripts in the near future.

**Collection Title**
Just Powers

**Collection Description**
TBD

**Manifest**
https://docs.google.com/spreadsheets/d/1eV6Vu_fx_JpYcy0GsJyIVYWvv5KUgM7l2inNiEcdE0o/edit#gid=0

**Batch files**
To be provided by researchers.

**Comment by seanluyk** [comment]
@anayram did we ever receive the materials from this research team?

**Comment by anayram** [comment]
@seanluyk I did not but I did notice students are working on metadata right now. Should we check in with them to ask about progress?

**Comment by seanluyk** [comment]
@anayram may be worth checking in where they're at, to see if they need any assistance. I noticed that a few things are missing (e.g. genre), although it's otherwise looking pretty good. If they'd like to start getting this ingested I think we could accommodate that

**Comment by seanluyk** [comment]
Closing since we're documenting these in the repositories Trello board now: https://trello.com/c/mAgw96Cg
