### ISSUE TITLE
ERA A+V homepage look and feel

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#44]
Need to get time from Natasha when she is back to work on the homepage look and feel how we link ERA AV from ERA and we link ERA AV from the library website. Having a look and feel similar to ERA would be nice.

Some example Avalon websites
https://mdpi.iu.edu/
https://media.dlib.indiana.edu/
https://media.northwestern.edu/

**Comment by umarqasim** [comment]
Contacted Kenton and he has put this work on the list of tasks she will focus on after her return.

**Comment by seanluyk** [comment]
@nnunn and I met today to discuss this work. Natasha is going to begin work on this in April and run some ideas by us. Flagging @cwant to set up a meeting with Natasha to get access to dev

**Comment by cwant** [comment]
@nnunn Hey! :)

We can set you up with this. This (currently) can either be on a server Tai-chun has set up, or a Virtual Box/Vagrant VM instance.

**Comment by nnunn** [comment]
done in test.
