### ISSUE TITLE
Avalon 6 Landing page formatting issue

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#444]
### Descriptive summary

the landing page text on the avdev01 instance is too big and need to be reduced

### Expected behavior
the text size should be similar to what we have on the production instance

### Actual behavior
Showing text in large font

![landingpageissues](https://user-images.githubusercontent.com/2874660/55591663-57b48200-56f3-11e9-84a7-40912e772e41.gif)
### Steps to reproduce the behavior
check the dev instance at
https://avdev01.library.ualberta.ca/
### Related work

Link to related tickets or prior related work here.

**Comment by jefferya** [comment]
New look after tweaking font size:

![avalon-6-format](https://user-images.githubusercontent.com/879785/57390862-830b1080-717a-11e9-9f3b-f661c684d12d.jpg)

![avalon-6-format-2](https://user-images.githubusercontent.com/879785/57391267-63c0b300-717b-11e9-8161-36cc38cf2a63.jpg)

**Comment by jefferya** [comment]
@umarqasim The Avalon test and dev servers have a fixed version. Let me know if the fix addresses the concerns.
