### ISSUE TITLE
Avalon 6: Monitor resque service from the application

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/avalon#446]
We would like to have the application monitor the resque service (queue and workers) and restart it when it goes down or after a server reboot, so that this monitoring doesn't have to be done at the system level. Since this is unknown territory for us we've left this monitoring to be solved at the system level for now, but we want to revisit this when we have more information.

**Comment by umarqasim** [comment]
This page has some information and may help to resolve this issue.
https://wiki.dlib.indiana.edu/display/VarVideo/Monitoring+Avalon
