### ISSUE TITLE
Communication needed for launch

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#45]
- [x] appearance on UAL page (possibly under services or DI page)
- [x] appearance on ERA page
- [x] Intake form / deposit policy and procedures
- [x] Work with communication office for a communication plan.

**Comment by cwant** [comment]
This one can likely be closed.

**Comment by seanluyk** [comment]
@cwant agreed - closing. Meredith and I are meeting next week to discuss external communications, but the other items in this issue are already done
