### ISSUE TITLE
Batch Ingest - FIP 2019

### ISSUE THREAD

**Issue by anayram** [ualbertalib/avalon#450]
**Brief description of batch**
Available to the general public.
Addition to existing collection Forum for Information Professionals (FIP)

**Collection Title**
Forum for Information Professionals (FIP) collection
(existing)

**Collection Description**
n/a

**Manifest**
https://docs.google.com/spreadsheets/d/10Ja5trrJEPrezWjXFPDaVGGMATkjoUeuhIttQC9Gm1s/edit#gid=0

**Batch files**
https://drive.google.com/open?id=1nhRmXHWhbrosPQzdPnnSIa2AdTZ6I_EN
https://drive.google.com/open?id=1lcSNMww5wiLSzropshg20jvn2E5OTUJQ
https://drive.google.com/open?id=1Y2uk7ci1BGo2ghxGNKvNjmiTPWQoEReO
https://drive.google.com/open?id=12L6k-JtxSRB_zbdjheY9-d_vMPTxydaj
https://drive.google.com/open?id=1PIm0u-7M_41yo3ihRm4ytBkRYa6_PI5L
https://drive.google.com/open?id=1lGrw378T9ryDo1wvEcqYNsRMToX4faIq
https://drive.google.com/open?id=1TJnDWBNrimWr8ZU9jSp3mITsRE704wIE
https://drive.google.com/open?id=1lRBH4n6QTCLMfRR0LZZ8E0xd-M-GpzuW
https://drive.google.com/open?id=1R_UN_NYz2iT53DEl_9UZllfEHHfQQMB7

**Comment by anayram** [comment]
@umarqasim @kgrant1 has this been deposited yet?

If so, can we add the following info to this ticket?
Batch ingest id
Collection link for reference
Date batch was completed (optional)

**Comment by umarqasim** [comment]
No it hasn't been yet. Will provide you details as soon as done ingesting
this.

*--*
*Umar Qasim, PhD*
Digital Preservation Officer
2-10N Cameron Library | University of Alberta
Edmonton, Alberta T6G 2J8, Canada
Tel: 780-492-9861 | Fax: 780-492-9243
umar.qasim@ualberta.ca | http://www.umarqasim.ca

**Comment by kgrant1** [comment]
Completed.

Batch Ingest ID: (Will Check with Umar for this).
Collection Link: https://era-av.library.ualberta.ca/catalog?f%5Bcollection_ssim%5D%5B%5D=Forum+for+Information+Professionals+%28FIP%29
Date Completed: May 22, 2019

**Comment by anayram** [comment]
Thanks Kaitlyn!
