### ISSUE TITLE
Report/Survey of existing multimedia objects in ERA

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#49]
- [x] @zschoenb to send a report of zipped multifile objects that contains multimedia. 
- [ ] generate reports from ERA for multimedia objects.

**Comment by zschoenb** [comment]
[fileTypeReport.xlsx](https://github.com/ualbertalib/avalon/files/731084/fileTypeReport.xlsx)
[multipartreport.xlsx](https://github.com/ualbertalib/avalon/files/731085/multipartreport.xlsx)

**Comment by zschoenb** [comment]
[media files zipped in era](https://github.com/ualbertalib/avalon/files/900809/multipartreport_media_files.csv.zip)

Also, contains two instances where a zipped file contains media objects (i.e. a zipped file within a zipped file containing media objects)

@weiweishi

**Comment by zschoenb** [comment]
[multipart files containing media](https://github.com/ualbertalib/avalon/files/900817/multipartreport_media_files.csv.zip)


Also, contains two instances where a zipped file contains media objects (i.e. a zipped file within a zipped file containing media objects)

@weiweishi

**Comment by cwant** [comment]
Has the work for the second task above been completed? (I.e., can we close this issue?)

**Comment by seanluyk** [comment]
Doing some cleanup
