### ISSUE TITLE
Make Share button more noticeable 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#50]
The current share button from a record view is pretty hard to notice. I would recommend:
-Increasing font size
-If possible, moving closer to the centre of the page

**Comment by cwant** [comment]
Below is before/after of a couple tweaks:

* Make 'Share' button align with right side of the media;
* Set 'font-size' style to 'larger':

![issue_50_before](https://cloud.githubusercontent.com/assets/672104/24917239/c9db0d0c-1e99-11e7-8938-dd2fa5072fc5.png)
![issue_50_after](https://cloud.githubusercontent.com/assets/672104/24917240/c9dcbdbe-1e99-11e7-944d-ae5473adfc77.png)

**Comment by seanluyk** [comment]
Looks much better, thanks @cwant
