### ISSUE TITLE
Unable to Manage File for Con Hall Collection

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#512]
### Descriptive summary

When attempting to Manage File for any item in the Convocation Hall Collection (sound or video), clicking on Manage File results in an error page. I confirmed that this does not occur with other collections. For example, clicking on Manage File here leads to an error page:
![image](https://user-images.githubusercontent.com/14880206/63278420-76f81a00-c264-11e9-875a-0ba9c883dafb.png)

### Expected behavior
Clicking on Manage File works for all collections

### Actual behavior
Clicking on Manage File results in an error page

**Comment by weiweishi** [comment]
And this is the rollbar reporting of the issue:
https://rollbar.com/ualbertalib/avalon/items/160/

It shows: ```Errno::E2BIG: Argument list too long - /usr/sbin/lsof -Fcpan0``` with a huge file list. 
it's trying to call for the batch job when this occurs:
```
File "/var/www/avalon6/lib/avalon/batch.rb", line 40 in block (2 levels) in find_open_files
```
wondering why those files are deemed at open files.

**Comment by seanluyk** [comment]
Update: by moving an insane amount of files (10K+) into a new directory (/processed) I was able to resolve this issue. In the future, we'll create directories for single batches to avoid this issue.

Keeping this open for now if there are plans for more investigation. It would be good to know what the upper limit is regarding the number of files

**Comment by jefferya** [comment]
More information:

To reproduce:
- cd to the dropbox directory and into subdirectory for the desired collection
- create a number of file e.g., ` for i in {1..8000}; do touch "delete_$i.mp4"; done`
- go to the file upload step in the UI
- when `#{lsof} -Fcpan0 #{args}` is executed, the following error is triggered: `Errno::E2BIG (Argument list too long - /usr/sbin/lsof -Fcpan0 ...[list of files in previous step])`

I think the following is happening when the manage files page is triggered for the Convocation Hall collection:
- Rails view tries to determine if any of the files in the Convocation Hall dropbox directory are currently in-use (as per the command `lsof`) 
https://github.com/ualbertalib/avalon/blob/avalon-6/app/models/file_upload_step.rb#L28-L32
- the dropbox lib method: https://github.com/ualbertalib/avalon/blob/avalon-6/lib/avalon/dropbox.rb#L29
- this calls a method in the batch library (not sure why code organised this way) https://github.com/ualbertalib/avalon/blob/avalon-6/lib/avalon/batch.rb#L28-L48

The code the concatenates the list of files in the dropbox directory and adds to a shell exec of the lsof

One thought, the max length of a command-line arg exceeded however the command reported in the error log is 157243 bytes while `getconf ARG_MAX` reports `2097152` on avalon6.

**Comment by seanluyk** [comment]
Problem identified, closing.
