### ISSUE TITLE
Featured Content links point users to no search results found page when not logged in

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#514]
### Descriptive summary

Clicking on the [Featured Audio Collection](https://era-av.library.ualberta.ca/catalog?f%5Bavalon_resource_type_ssim%5D%5B%5D=Sound+Recording&f%5Bcollection_ssim%5D%5B%5D=Convocation+Hall+) and [Featured Item](https://era-av.library.ualberta.ca/catalog?q=%22+An+Evening+with+Edward+Snowden+on+Security%2C+Public+Life+and+Research%22) links lead non-logged in users to a "no results" page

### Expected behavior
- Clicking these links directs non-logged in users to SAML authentication page

### Actual behavior
 - Clicking these links leads to a no results found page because users need to be logged in to see these results

### Additional Context
 - Links for these collections need to be constructed that will work for both logged in, and non-logged in users

**Comment by pbinkley** [comment]
Presumably this is because the Con Hall collection and the Snowden video are restricted to U of A users. They don't show up in search results or the facet lists for non-logged-in users either. Would you care to an open collection and item to replace them?

**Comment by seanluyk** [comment]
@pbinkley it should be possible to redirect users to the SAML login page. If not, we'll need to replace these with some open collections...these two, unfortunately, can't be made open

**Comment by pbinkley** [comment]
@seanluyk ah, sorry, I overlooked your expected behavior. We'll need to do some digging to determine how to build a url that takes them to the login page and then redirects to the featured page once they're logged in. That will still mean that these featured links are only useful to U of A users.

**Comment by seanluyk** [comment]
@pbinkley no worries, and thanks!

**Comment by seanluyk** [comment]
Closing as this is no longer an issue - we updated the featured audio collection link long ago
