### ISSUE TITLE
[Avalon] Move avalon-6 branch to master

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#515]
### Descriptive summary
Now we've completed the avalon 6 migration, I wonder if we should move the avalon-6 as our master branch, and move the current master to a new avalon-5 branch just in case we still need the code. We are very far off the upstream code. so connections to upstream branches are not a concern.

**Comment by jefferya** [comment]
To move branch avalon-6 to master:
- tried to git merge but `fatal: refusing to merge unrelated histories` error

Rename might be a better approach:
- <https://www.hostinger.com/tutorials/how-to-rename-a-git-branch/>

Rename master to avalon-5 and update remote
```
git checkout master
git branch -m ualbertalib/avalon-5
git push origin :master ualbertalib/avalon-5
git push origin -u ualbertalib/avalon-5
```
Rename avalon-6 to master
```
GitHub set default branch to branch other than avalon-6
git branch -m avalon-6 master
git push origin :avalon-6 master
git push origin -u master
GitHub set default branch to master
```

**Comment by weiweishi** [comment]
- branch name may impact the rpm rebuild process
- dependabot looks to the default branch

**Comment by jefferya** [comment]
- [x]  From Tai Chun: `The RPM package build file will do git checkout v%{version} so as long as the version tag is on the correct branch there's no impact on the existing process.`
- [x] Updated Dependabot: https://app.dependabot.com/accounts/ualbertalib/projects/31105
- [x] Update DI documentation
