### ISSUE TITLE
Playback issues on mobile device

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#518]
### Descriptive summary
Occasionally, media doesn't load/play on a mobile device with auto quality selected. Oddly, this isn't consistent between different media files. Accessing from Google Pixel on UWS and home Wifi from Chrome

### Expected behavior
Media loads/plays consistently irrespective of device in auto mode 

### Actual behavior
Clicking play does nothing

### Steps to reproduce the behavior
1. View ERA A+V as desktop site on mobile device (to allow SAML login)
2. Go to https://era-av.library.ualberta.ca/media_objects/s7526c93c
3. Click play. Notice that the media file does not load or play back  

### Additional Context
- Changing quality to high or medium seems to resolve the issue

**Comment by jefferya** [comment]
Able to reproduce with Andriod 10, Chrome 76.0.3809.132 with audio (not video)

**Comment by ConnorSheremeta** [comment]
Thanks Jeff, opened up a ticket upstream here: https://github.com/avalonmediasystem/avalon/issues/3562

**Comment by ConnorSheremeta** [comment]
Putting this on the icebox for now as this is yet to be resolved, will be checking upstream to see if anything comes from the created issue

**Comment by seanluyk** [comment]
Was about to contact Jon Cameron and I noticed that he referenced our issue here in this mega-issue about streaming playback issues: https://github.com/avalonmediasystem/avalon/issues/3518

It looks like this is fairly well documented on their end, and they're investigating a number of known issues related mobile playback

**Comment by ConnorSheremeta** [comment]
This issue has been resolved upstream! https://github.com/avalonmediasystem/avalon/pull/4186

Should be in the v7.1.2/7.2 release. However, this fix is a small code change, should we backport this?

**Comment by ConnorSheremeta** [comment]
I should've tagged you two regarding the message above @jefferya @seanluyk

**Comment by jefferya** [comment]
Before PR #677, https://github.com/ualbertalib/avalon/pull/682/commits/48263d94df305b2e31d9a8107e6cec2dc008e599

![Screenshot from 2021-03-18 11-24-11](https://user-images.githubusercontent.com/879785/111669878-d883c000-87dc-11eb-885f-fa0373ce0015.png)


After fix, thumbnail appears and one can play the media

![Screenshot from 2021-03-18 11-17-37](https://user-images.githubusercontent.com/879785/111669894-dd487400-87dc-11eb-99a6-720f2b389b51.png)

**Comment by jefferya** [comment]
Tested on Pixel 2, Android 11, Chrome 89.0.4389.90.  
* example in original issue played: https://era-av.library.ualberta.ca/media_objects/s7526c93c

Note: This is unrelated but happened across while testing:
[1] https://www.theverge.com/2021/3/22/22345696/google-android-apps-crashing-fix-system-webview
