### ISSUE TITLE
Update ERA A+V OpenSearch description

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#519]
### Descriptive summary
It would be good to update ERA A+V's OpenSearch description. We should change "Search era-av.library.ualberta.ca" to "Search ERA A+V" 

### Related work
[Discovery#1243](https://github.com/ualbertalib/discovery/issues/1243)

**Comment by pgwillia** [comment]
The OpenSearch description is tied to the application name.  This is where I would have expected it to be set: https://github.com/ualbertalib/avalon/blob/667b8042d078232b88a7f63f4c67cb4ef77957fb/config/locales/blacklight.en.yml#L3

But instead it's being set from: https://github.com/ualbertalib/avalon/blob/667b8042d078232b88a7f63f4c67cb4ef77957fb/app/helpers/application_helper.rb#L17-L19

https://github.com/ualbertalib/avalon/blob/667b8042d078232b88a7f63f4c67cb4ef77957fb/config/settings.yml#L1

Blacklight sets it here: https://github.com/projectblacklight/blacklight/blob/a923db47b0651b2e7549575e9f2e328b9d7da159/app/views/catalog/opensearch.xml.builder#L5-L6

I think this is a duplicate @seanluyk 

Blocked by #541

**Comment by pgwillia** [comment]
from https://era-av.library.ualberta.ca/catalog/opensearch.xml

```
<OpenSearchDescription><ShortName>ERA_A+V</ShortName><Description>ERA_A+V Search</Description><Image height="16" width="16" type="image/x-icon">https://era-av.library.ualberta.ca/assets/favicon-b4185c7dd08c0b4f2142c58bbcca322b3a01f50adc3413438b98be2b664bb4b6.ico</Image><Contact/><Url type="text/html" method="get" template="https://era-av.library.ualberta.ca/catalog?q={searchTerms}&amp;page={startPage?}"/><Url type="application/rss+xml" method="get" template="https://era-av.library.ualberta.ca/catalog.rss?q={searchTerms}&amp;page={startPage?}"/><Url type="application/x-suggestions+json" method="get" template="https://era-av.library.ualberta.ca/catalog/opensearch.json?q={searchTerms}"/></OpenSearchDescription>
```

It looks like this is already the same as the application name problem in the other ticket.

**Comment by seanluyk** [comment]
@pgwillia not quite a duplicate, although related to #541. Here's what I see in my browser:
![image](https://user-images.githubusercontent.com/14880206/66426818-a9aacd00-e9e0-11e9-8177-1215911e5473.png)

**Comment by pgwillia** [comment]
@seanluyk I suspect that might be an old reference?  Could you walk me through how you added opensearch for avalon?

**Comment by seanluyk** [comment]
@pgwillia I didn't add it..it was probably Chris?

**Comment by pgwillia** [comment]
Some more context that I found out from talking with Sean
> Once Chromium has determined it can search a site, any time the user types the URL of the site into the Omnibox the user is offered the ability to search the site. Once the user presses tab, then types in a string and presses the enter, the site is searched and the results shown to the user.
https://www.chromium.org/tab-to-search
