### ISSUE TITLE
Avalon batch ingest script changes

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#52]
Batch Ingest script changes
Related Item and related Item label
- when we start ingesting, the url is not available if the related item is in the same manifest
- Either we put in fake urls or make the url field as optional
- another option is to make predictable urls before ingest based on an ID
- Can we do a batch update

Contributor role
- how can we assign multiple roles to a single contributor

Bibliographic ID
- System chokes on using this during batch ingest

Other Identifier
- How system is applying labels depending on the type of other identifier

Creator
- This seems to be mapping to main contributor on the Avalon interface
- There is no option to enter a role for this
- Needs devleopment

Agreement checkbox
- are we storing this filed in the backend
- should we

Terms of Use
- Choose a license filed is not linked to this
- We need a new field in the manifest or link the terms of use field to "license field"

Choose a license
- Not linked to any field in the batch ingest template
- It is a required filed in the interface but not being enforced during ingest

Topical Subject
 - It is a required filed in the interface but not being enforced during ingest

Language
- It is a required filed in the interface but not being enforced during ingest

**Comment by seanluyk** [comment]
Bibliographic ID configuration appears to be missing from the resource description form is TEST, which may explain why. Also, this has not been pushed to PROD.

**Comment by danydvd** [comment]
@cwant if you are happy with breakdown of this ticket (see #80 #81 #82 #83 #84 #85), I think it can be closed.

**Comment by seanluyk** [comment]
Doing some cleanup
