### ISSUE TITLE
Mobile: media quality selector cuts off options (audio; auth: logged out)

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#531]
### Descriptive summary

On a mobile device with no user logged in, the audio quality selection list is cutoff (top and bottom). When the user is logged in, auto/high/medium display. 

### Expected behavior

- list of auto/high/medium/low

### Actual behavior

- list high/medium with auto cutoff

### Steps to reproduce the behavior

- https://era-av.library.ualberta.ca/media_objects/s7526c93c
- Chrome DevTools or mobile device 
- Select any audio
- select the audio playback button (gear) -- only high/medium display (auto cut-off in the interface)

### Related work

#518 (possibly)

**Comment by ConnorSheremeta** [comment]
https://github.com/avalonmediasystem/avalon/issues/3503
