### ISSUE TITLE
Understand how batch update works in ERA-AV

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#534]
### Descriptive summary
- [x] verify if an updated manifest upload will trigger a batch update?
  - needs chron job (or manual invocation) see #532 for details 
- [x] how manifest for update differs from regular batch ingest? (needs to provide item ids etc? )
  - Replay name sent in e-mail; Only unplublished media; manifest equivalent to original with any needed changes [Troubleshooting a Batch Ingest](https://wiki.dlib.indiana.edu/display/VarVideo/Troubleshooting+a+Batch+Ingest)
- [x] create internal documentation for how batch ingest process works.
  -  [Troubleshooting a batch ingest](https://wiki.dlib.indiana.edu/display/VarVideo/Troubleshooting+a+Batch+Ingest)
  - [Batch ingest](https://wiki.dlib.indiana.edu/display/VarVideo/Batch+Ingest+Package+Format#BatchIngestPackageFormat-Introduction)
  - [Batch ingest package format](https://wiki.dlib.indiana.edu/display/VarVideo/Batch+Ingest+Package+Format#BatchIngestPackageFormat-Introduction) 
  - [DI documentation ingest failure](https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/avalon/avalon_documentation.md#ingest-failures)
  - [DI documentation monitoring](https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/avalon/avalon_documentation.md#logs-monitoring-and-diagnostics)

**Comment by jefferya** [comment]
DI Internal updated with details <https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/avalon/avalon_documentation.md#batch-ingest>

Assuming internal documentation is beyond the Dev group, is this correct?
