### ISSUE TITLE
Update featured audio collection link

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#536]
### Descriptive summary

Due to the limitation of linking to authenticated collections using a solr query, we need to change the featured audio collection link to an OA collection link

Change featured audio collection link (https://era-av.library.ualberta.ca/catalog?f%5Bavalon_resource_type_ssim%5D%5B%5D=Sound+Recording&f%5Bcollection_ssim%5D%5B%5D=Convocation+Hall+) accordingly:

 - Change link to https://era-av.library.ualberta.ca/?_=1566927132466&f%5Bavalon_resource_type_ssim%5D%5B%5D=Sound+Recording&f%5Bcollection_ssim%5D%5B%5D=Edmonton+Mennonite+Centre+for+Newcomers+%28EMCN%29

 - Change label to Edmonton Mennonite Centre for Newcomers (or just World of Story Collection if it doesn't fit)

### Related work

#529 #514

**Comment by pgwillia** [comment]
@seanluyk what is the significance of having ?_=1566927132466 in the link?

**Comment by pgwillia** [comment]
For the label, is there a preference?
![Screenshot from 2019-09-05 15-04-42](https://user-images.githubusercontent.com/1220762/64380592-8d390080-cfee-11e9-8976-31e3160edf7c.png)
![Screenshot from 2019-09-05 15-04-23](https://user-images.githubusercontent.com/1220762/64380594-8d390080-cfee-11e9-9bed-2549cb28be67.png)

**Comment by pgwillia** [comment]
> For the label, is there a preference?

In haste this screenshot has the change in the Featured Video Collection rather than the Audio Collection.  Use your imagination.  I'm just looking for feedback about if the full name "fits" or not.

**Comment by seanluyk** [comment]
@pgwillia that's a good question re:  ?_=1566927132466 in the link. I'm not sure, to be honest, but I Avalon adds this when you facet to a specific collection for some reason?

**Comment by seanluyk** [comment]
@pgwillia re: the label, let's go with World of Story Collection, thanks!

**Comment by pbinkley** [comment]
So the question is whether a two-line label is ever acceptable?

**Comment by seanluyk** [comment]
@pbinkley two-line is OK with me, but I'm thinking that World of Story is just better anyways
