### ISSUE TITLE
batch ingest: if language not recognised in manifest no user feedback 

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#539]
### Descriptive summary

A user creates a batch ingest manifest with a language not recognized and the batch ingest initiated, the batch ingest silently fails.

### Expected behavior
- batch ingest processes the manifest file and e-mails user with a validation error. E.G., if the user_id in the batch is not valid the avalon notification e-mail is notified. 

### Actual behavior

- batch ingest starts
- sends e-mail the the batch is added to the queue
- user receives no feedback
- the system logs report

```
[ActiveJob] [IngestBatchEntryJob] [e7b262a6-b754-4967-bb45-c1aef4c06600]   SQL (0.3ms)  UPDATE `batch_entries` SET `error` = 1, `current_status` = 'Invalid Entry', `error_message` = 'Language Language not recognized (Cherokee-Sprache)', `updated_at` = '2019-08-28 18:01:33' WHERE `batch_entries`.`id` = 9
[ActiveJob] [IngestBatchEntryJob] [e7b262a6-b754-4967-bb45-c1aef4c06600]    (10.7ms)  COMMIT
```

### Steps to reproduce the behavior

- copy the following manifest file into the dropbox directory in a test collection and run the batch ingest
[ERA a+v Batch Ingest - v. 02 - Radioactive Item.xlsx](https://github.com/ualbertalib/avalon/files/3552794/ERA.a%2Bv.Batch.Ingest.-.v.02.-.Radioactive.Item.xlsx)

### Related work

#533

**Comment by anayram** [comment]
We got a notification email for a batch where a language-field validation error was reported.

See email titled "Errors Present: Batch Registry Truck 6 Pt 4 - 2011.xlsx for Convocation Hall has completed"

Could it be possible that you did not get a notification because the email in the manifest was set as archivist1@example.com?

**Comment by jefferya** [comment]
@anayram 

Yes, possible.
