### ISSUE TITLE
Out of date solrconfig.yml

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#54]
The ansible playbook has an out of date solrconfig.yml. I believe this file gets installed from the archive in the playbook repository at:

projects/avalon/roles/avalon_solr/files/master.zip

It gets installed to /usr/local/solr/avalon/conf/solrconfig.xml.

The current version of this file is at:

https://github.com/ualbertalib/avalon/blob/master/solr_conf/conf/solrconfig.xml

The lines related to 'section_label_tesim' allows for searching of structured metadata (and are required for the test suite to pass).

**Comment by cwant** [comment]
Perhaps there is a way for this file to be copied from the avalon repository to the solr install location, post-install?

**Comment by taichun** [comment]
Chris:

Have you tested this solrconfig.xml with the particular version of solr
Avalon currently uses? If everything tested successfully then we can
implemented this with Ansible playbook.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by cwant** [comment]
Hi Tai-chun,

Yes, I have tested the changed config, and it works. The number of changed lines is pretty small, the new lines allow some additional fields related to structural metadata to be found in searches:

<pre>
$ diff solrconfig.xml /usr/local/solr/avalon/conf/solrconfig.xml 
57,61c57
<           title_tesi^10.0
<           section_label_tesim^5.0
<           creator_ssim^3.0
<           date_sim^3.0
<           all_text_timv^1.0
---
>           all_text_timv
66,70c62
<           title_tesi^10.0
<           section_label_tesim^5.0
<           creator_ssim^3.0
<           date_sim^3.0
<           all_text_timv^1.0
---
>           all_text_timv^10
135a128,133
>        
</pre>

**Comment by taichun** [comment]
Chris:

Is this updated solrconfig.xml required for v5.1.5.20170201.uofa release?

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by taichun** [comment]
More importantly, does updating this solrconfig.xml requires re-index in
current production stack?

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Libraries
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by cwant** [comment]
Hi Tai-chun,

1) This is not required for the upcoming release, and can be updated
independently of the release cycle.
2) I'm no solr expert, but I would think that restarting tomcat should be
sufficient to get this to work. If not, I can give you the commands
required to reindex solr at the rails console, if you don't know them
already (there may also be a rake task that can be run).

Chris
