### ISSUE TITLE
Resource Description Page - Validation not working upon save

### ISSUE THREAD

**Issue by anayram** [ualbertalib/avalon#545]
### Descriptive summary
Validation of controlled vocabularies is not triggered when saving metadata in Resource Description Form. Invalid forms or next partial matches are selected and saved.
Chrome Version 76.0.3809.132 (Official Build) (64-bit)
Ubuntu 19.04 

### Expected behavior
When user hits 'Save' or 'Save and Continue' buttons:
- [x] 1. validation should be triggered for controlled vocabulary fields and
- [x] 2. validation errors should be reported to users for correction

### Actual behavior

- Validation is not triggered upon save and no feedback is provided to users.
- For genre terms - invalid term is saved
- For language terms - typing language returns partially matched list of items and form selects first language in list - related to #68 

### Steps to reproduce the behavior
1. Go to test item https://era-av.library.ualberta.ca/media_objects/9s1617241 and click Edit
3. Go to Resource Description tab
4. Edit Genre field with some invalid term or alternate capitalization like "documentary"
5. Edit Language field with some invalid term like "mo"
6. Save Form and click on Preview tab to see results

### Related work
Related to #68

**Comment by pgwillia** [comment]
I suspect that there's something in here
https://github.com/ualbertalib/avalon/blob/05ca1c804cb5ef5809dae9d3fae2ab69eef1bdbc/app/controllers/media_objects_controller.rb#L211-L224

**Comment by pgwillia** [comment]
Genre with alternate capitalization is permitted by the application here
https://github.com/ualbertalib/avalon/blob/05ca1c804cb5ef5809dae9d3fae2ab69eef1bdbc/app/models/genre_term.rb#L30
https://github.com/ualbertalib/avalon/blob/05ca1c804cb5ef5809dae9d3fae2ab69eef1bdbc/app/models/genre_term.rb#L57-L59

**Comment by pgwillia** [comment]
Some of the text_fields use [typeahead](https://github.com/corejavascript/typeahead.js) to provide a selection list. Hoping the customization might yield a better flow for the user.
https://github.com/ualbertalib/avalon/blob/05ca1c804cb5ef5809dae9d3fae2ab69eef1bdbc/app/assets/javascripts/autocomplete.js.coffee#L26-L60
