### ISSUE TITLE
Player controls cut off text - auto-hide controls during playback

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#55]
Not sure if this is video specific or an issue with mediaelement.js, but here's the issue:

The player controls do not seem to auto-hide during playback. This isn't normally an issue, except for text heavy videos such as this one:

https://era-av.library.ualberta.ca/media_objects/avalon:1145

In regular and full screen modes, text at the bottom of the video is cut off.

There could be something wonky with this specific video, but in any case, I think it's best for the player controls to auto-hide in regular and full screen modes if this is possible and have controls appear on mouse hover.

**Comment by cwant** [comment]
Hi Sean,

I am getting auto-hide of controls for the video in question. It's a little quirky though, the controls appear to show all the time, until you hover inside the video, then take your mouse outside of the player region.

Does this match what you are seeing?

Cheers,
Chris

**Comment by seanluyk** [comment]
I wasn't able to figure out how to auto-hide the controls, so any way to make it less quirky would be great!

**Comment by umarqasim** [comment]
same here, not able to see auto-hide working after moving mouse away.

*--*
*Umar Qasim, PhD*
Digital Preservation Officer
2-10N Cameron Library | University of Alberta
Edmonton, Alberta T6G 2J8, Canada
Tel: 780-492-9861 | Fax: 780-492-9243
umar.qasim@ualberta.ca | http://www.umarqasim.ca

**Comment by cwant** [comment]
Some code has been deployed to the test stack. Compare, for example, this:

https://avalon-test.library.ualberta.ca/media_objects/avalon:35
vs
https://era-av.library.ualberta.ca/media_objects/avalon:1145

**Comment by umarqasim** [comment]
it seems to be only working in a normal size window but not in the full screen mode.

**Comment by cwant** [comment]
Okay, will need to think about this for full screen. Technically, the mouse never leaves the window during full screen so we might need to implement a timer based on how long the mouse is stationary.

**Comment by cwant** [comment]
Okay, please try the test video again (of any others on the test server):

https://avalon-test.library.ualberta.ca/media_objects/avalon:35

Full screen: controls hide after no mouse movement for two seconds.

**Comment by umarqasim** [comment]
is it possible to apply the same in a regular screen mode. In full screen mode it is working fine.

**Comment by cwant** [comment]
Alright, updated to make the mouse movement behavior (hide after two seconds) work in normal-size mode too.

**Comment by umarqasim** [comment]
Works perfect :)

Thanks

**Comment by seanluyk** [comment]
Hmmm...I still can't get a video to play in TEST. When I'm in Cameron at 2 I'll try on the consult room computer.

**Comment by cwant** [comment]
@taichun Can you make sure that the test streaming server is accessible to connections from Rutherford library?

**Comment by seanluyk** [comment]
In the category of unintended consequences, the auto-hide functionality that I requested is problematic for audio only items. For example https://era-av.library.ualberta.ca/media_objects/avalon:1252

It's a little weird to not see anything when the audio is playing but it isn't for video for some reason. I wonder if it's possible to not hide for audio items?

**Comment by cwant** [comment]
Hi Sean, I've worked on a patch for this that should go in the next release when @taichun gets back from vacation

You can review on the test server that both audio and video do the right thing:

Audio: https://avalon-test.library.ualberta.ca/media_objects/avalon:50
Video: https://avalon-test.library.ualberta.ca/media_objects/avalon:13

**Comment by seanluyk** [comment]
Perfect, looks great!
