### ISSUE TITLE
Adding robot.txt to ERA-AV

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#556]
### Descriptive summary

ERA-AV needs a robot.txt file. We can use an example from ERA as a starting point. Additional things to consider:
- how to instruct bots to avoid auto downloading of the media stream

**Comment by weiweishi** [comment]
might need to add a top level robots.txt in avstream.library.ualberta.

**Comment by weiweishi** [comment]
- [ ] add robots.txt to media streaming server
- [ ] NO_FOLLOW meta tag for the links

**Comment by weiweishi** [comment]
@taichun can we have a quick chat to see if we can add a robots.txt to wowza?

**Comment by taichun** [comment]
avstream.library.ualberta.ca is a VIP that's resolved to the IST load
balancer. Not sure how to implement a robot.txt there.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Library
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438
