### ISSUE TITLE
Add "Ingest batches" button.

### ISSUE THREAD

**Issue by cwant** [ualbertalib/avalon#56]
### Add a button to ingest any batches that have been uploaded via dropbox.

Currently, if Umar would like to trigger the batch ingestion process, he has to contact either myself or Tai-chun to run a rake task at the console ("bundle exec rake avalon:batch:ingest"). This is something that could be handled via a button on the web interface.

**Comment by cwant** [comment]
Within the scope of this story, I am adding some enhanced batch logging, and a button to show the most recent batch ingest log.

**Comment by seanluyk** [comment]
That's great, @cwant
