### ISSUE TITLE
Unable to delete items from a playlist

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#566]
### Descriptive summary

When attempting to delete an item from a playlist, there is no yes option in the dialog box.
![image](https://user-images.githubusercontent.com/14880206/66077556-68687800-e51d-11e9-932d-b47bd7ceb7d5.png)

### Expected behavior
Both yes and know options appear and work as expected = yes deletes item, no doesn't

### Actual behavior
There is no "yes" option
### Steps to reproduce the behavior

1. Creat playlist
2. Add some items
3. Attempt to select and delete an item
4. Notice behaviour

**Comment by jefferya** [comment]
Problem area: 
https://github.com/ualbertalib/avalon/blob/avalon-6/app/assets/javascripts/button_confirmation.js.coffee#L34
