### ISSUE TITLE
[Spike]Testing Bibliographic metadata from catalogue through Zoom/Z39.50

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#568]
### Descriptive summary

We'd like to test the bibliographic record import again in the UAT/Test environment. Some related past issues are #13 #82

**Comment by seanluyk** [comment]
@weiweishi considering this as a spike, with the caveat that we're interested in using this for new items/submission, not editing

**Comment by jefferya** [comment]
From meeting with Mariana:

Question for the team:
* What should the z39.50 source be? Should ERA A+V use UAL's Catalog / Unicorn server? Or LOC? Or another?

Testing process (assume UAL server for testing) :
* via batch ingest
  * create batch manifest file
    * fill in only the following fields: bibliographic ID and the masterfile path
      * bibliographic ID: from the UAL catalog lookup item, use the unicorn id - from the url
        * For example: https://search.library.ualberta.ca/catalog/1760346 ==> unicorn id: 1760346
  * after batch ingest, compare metadata
    * pay particular attention to the terms of use / license (see MODS as it offers distinction)
* via UI
  * removed UI component in #373
    * should this decision be reversed?

Current ERA A+V config:
```
SETTINGS__BIB_RETRIEVER__PROTOCOL="z39.50"
SETTINGS__BIB_RETRIEVER__HOST=${UAL_z39_50_UNICORN_SERVER}
SETTINGS__BIB_RETRIEVER__PORT="2200"
SETTINGS__BIB_RETRIEVER__DATABASE="Unicorn"
SETTINGS__BIB_RETRIEVER__ATTRIBUTE="12"
```

Other tools to help with z39.50 debugging
* [Yaz](https://software.indexdata.com/yaz/doc/yaz-client.html)
* MarcEdit

**Comment by jefferya** [comment]
Initial findings for the config/setup:

Some or all of the following env vars required. Example: `docker-compose.yml`
```
      - SETTINGS__BIB_RETRIEVER__PROTOCOL=z39.50
      - SETTINGS__BIB_RETRIEVER__HOST=${ual_unicorn_z39.50}
      - SETTINGS__BIB_RETRIEVER__PORT=2200
      - SETTINGS__BIB_RETRIEVER__DATABASE=Unicorn
      - SETTINGS__BIB_RETRIEVER__ATTRIBUTE=12
      - SETTINGS__BIB_RETRIEVER__RETRIEVER_CLASS=Avalon::BibRetriever::Zoom
      - SETTINGS__BIB_RETRIEVER__RETRIEVER_CLASS_REQUIRE=avalon/bib_retriever/zoom
```

Install `yaz` z39.50 library. In the Docker context, modify: `bin/docker-start`:
```
pt-get clean && rm -rf /var/lib/apt/lists/; 
apt-get update
# Note: need libyaz4-dev otherwise yaz-config not found: apt-cache search yaz;
apt-get install -y yaz libyaz4 libyaz4-dev;
#yaz-config --help
# cat /usr/local/bundle/extensions/x86_64-linux/2.5.0/zoom-0.5.0/gem_make.out
```

An example to test if z39.50 connecting using <https://search.library.ualberta.ca/catalog/8127126>

```
require 'avalon/bib_retriever/zoom'
bib_id=8127126
Avalon::BibRetriever.instance.get_record(bib_id)
```

**Comment by seanluyk** [comment]
@jefferya @anayram re: Z39.50 source. I think the UofA catalog?

**Comment by jefferya** [comment]
Process described above. Will reopen if needed.
