### ISSUE TITLE
Length of file incorrect in ERA A+V

### ISSUE THREAD

**Issue by hhpicker** [ualbertalib/avalon#571]
### Descriptive summary

I have uploaded a file to ERA A+V - https://era-av.library.ualberta.ca/media_objects/6q182k57v. It is "Ye Banks and Braes". It shows up in the metadata record as 0:08 seconds long while the file is actually 2:20 minutes.

### Expected behavior

The file should show up as 2:20 minutes long in the playlist view.

### Actual behavior

The file shows up at 0:08 seconds long in the playlist view.

### Steps to reproduce the behavior

1. Look at the playlist view, see that "Ye Banks and Braes" is listed as 0:08 seconds long.
2. Play the file. You will see that it is actually 2:20 minutes.

**Comment by seanluyk** [comment]
@weiweishi could be isolated issue to this file, don't spend too much time on it
