### ISSUE TITLE
Related item borken URL discoverarchives.library.ualberta

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#574]
### Descriptive summary

Related item metadata points to a broken URL: discoverarchives.library.ualberta for he following resource: <https://era-av.library.ualberta.ca/media_objects/2j62s5487>

* https://discoverarchives.library.ualberta.ca/index.php/ernest-c-manning-oral-history-collection-transcript-of-interview-1
* https://discoverarchives.library.ualberta.ca/index.php/ernest-c-manning-oral-history-collection-audio-recording-of-interview-1

**Comment by sfarnel** [comment]
@jefferya discoverarchives is temporarily unavailable (known issue) and so this is likely related to that
