### ISSUE TITLE
Rollbar #185: find_for_lti

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#582]
<https://rollbar.com/ualbertalib/avalon/items/185/?item_page=0&item_count=100&#instances>

```
NoMethodError: undefined method `uid' for nil:NilClass (Most recent call first)
File /var/www/avalon6/app/models/user.rb line 77 in find_for_lti
File /var/www/avalon6/app/controllers/users/omniauth_callbacks_controller.rb line 51 in find_user
File /var/www/avalon6/app/controllers/users/omniauth_callbacks_controller.rb line 43 in action_missing
```

The list of occurrences appears to be mainly from the Google IP range via GoogleBot. 
An example: <https://era-av.library.ualberta.ca/users/auth/lti/callback?target_id=z029p546h>

@seanluyk: is the a means to check if the LTI is working? 

Could these Rollbar errors be due to deleted objects and thus Google has a stale cache of ERA A+V causing Google to crawl objects no longer in ERA A+V?

**Comment by jefferya** [comment]
Note from Sean:

> This can be tested from a Sandbox in eClass. I've added you to the LTI test course in eClass, and instructions for testing LTI are here: https://docs.google.com/document/d/13rgix7LgFAIEUK0KK98znp5t_YtyGU4mTO2NmV5t2oI/edit. It does look like this isn't working properly, although the demand for this is currently non-existent, although we should try to fix it anyway. 

Investigation results:
* LTI configuration needs updating; unsure what the proper values should be. Online documentation vague <https://wiki.dlib.indiana.edu/display/VarVideo/LTI+Integration>

**Comment by jefferya** [comment]
Next steps:
* update env config on avalon6-test based on Avalon 5 (config/lti.yml)
* update documentation
* test

**Comment by jefferya** [comment]
Adding the following three env variables moves the needle (i.e., fix noMethodError) in the test <https://eclass.srv.ualberta.ca/mod/lti/view.php?id=3904729> however, the media player is not loading. 

```
diff /etc/httpd/conf/avalon6_env.conf /etc/httpd/conf/avalon6_env.conf.bak01 
< #LTI
< SetEnv LTI_SERVERS eclass.srv.ualberta.ca
< SetEnv LTI_AUTH_KEY key
< SetEnv LTI_AUTH_SECRET xxxxxxxxxx
```

Investigating.

**Comment by jefferya** [comment]
avalon6-test setup with above config. Needed to clear browser cache (was logged into Avalon prior to eClass and this might have caused some confusion or avalon6-test is a haproxy and I only updated one member)

**Comment by taichun** [comment]
Hi, Jeff:

Avalon6 test stack is with all single servers so no haproxy involved. There
are many "left over" contents from before we migrated to HLS protocol, i.e.
They use RTMP protocol so the media player won't play them. Ingest a new
media object and it should stream normally.

Best regards,

Tai-chun Lee

UNIX System Administrator
University of Alberta Library
4-30 Cameron Library
Edmonton, Alberta
Canada T6G 2J8

Office: 780-248-1438

**Comment by weiweishi** [comment]
Change to configuration deployed into production. issue fixed
