### ISSUE TITLE
Rollbar #239: Validation failed: Terms of use not recognized (http://creativecommons.org/licenses/by/4.0/

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#583]
<https://rollbar.com/ualbertalib/avalon/items/239/?item_page=0&item_count=100&#instances.

Error might indicate the validation of the Terms of Use field for the resource is malfunctioning when a custom terms of use is selected. 

One weirdness, the [License file](https://github.com/ualbertalib/avalon/blob/a975c089674adf1a727ba43ebe0565400a221b6f/config/license.yml), in particular, the CC BY 4.0 uri is 'https' while others are 'http'. Is this correct?

This triggers the validation error as the validation assumes any custom terms of use doesn't start with a URI (i.e., http) or if the terms of use starts with http then contents match a URI within the license.yml file. Since the CC BY 4.0 URI is https instead of http, the match to license.yml fails, and the validation fails triggering the Rollbar notice. The [terms of use validation code link](https://github.com/ualbertalib/avalon/blob/a975c089674adf1a727ba43ebe0565400a221b6f/app/models/media_object.rb#L127-L132) 

The Rollbar error might be triggered by a publish action. Might be related to Rollbar #130 as well.

```
ActiveFedora::RecordInvalid: Validation failed: Terms of use not recognized (http://creativecommons.org/licenses/by/4.0/) (Most recent call first)
Show 3 non-project frames
File /var/www/avalon6/app/models/media_object.rb line 198 in publish!
File /var/www/avalon6/app/controllers/media_objects_controller.rb line 427 in block in update_status
File /var/www/avalon6/app/controllers/media_objects_controller.rb line 413 in each
File /var/www/avalon6/app/controllers/media_objects_controller.rb line 413 in update_status
```

**Comment by jefferya** [comment]
* scope: internal UAL users editing existing items; metadata quality
* impact: prevents user from saving; returns validation error

**Comment by weiweishi** [comment]
proposed solution:
- use https for the validation, change the License file
- update the metadata for objects to reflect the change.

**Comment by weiweishi** [comment]
will check with @anayram to estimate the amount of data cleaning required (which items have the license file with http, instead of https)

**Comment by anayram** [comment]
Thanks @weiweishi. It should be a very easy fix. I can work on this tomorrow and let you know.

**Comment by anayram** [comment]
@weiweishi looks like there are at least 161 resources with a CC license or statement that don't use `https`. 4 resources do use `https`. This count is based on solr results. If confirmation is needed, we would need to check mods records from fedora.

Let me know how you'd like to proceed. I have done this type of cleanup before by fetching mods files, cleaning them up, then pushing the new version to fedora directly. However, this is a production server, so let me know any other methods you might prefer.

**Comment by seanluyk** [comment]
@anayram this came up today in discussion with the Archives regarding their preferred license for the Jeet pilot (details in separate message). It does appear that any item with a CC-BY licenses didn't migrate over properly (shows as http://creativecommons.org/licenses/by/4.0). Newly created items don't have this issue/validate properly. Here are some examples from different collections:

1. https://era-av.library.ualberta.ca/media_objects/0v8381091

2. https://era-av.library.ualberta.ca/media_objects/rf55z8124

3. https://era-av.library.ualberta.ca/media_objects/jd472w969

Could you generate a list from the mods metadata? I could then assign this take to a staff member to click through those records and apply the proper license. This would be separate from the fix to the yml file

**Comment by anayram** [comment]
@seanluyk 
I've dumped a report of all items (about 178) containing a creative commons URI:
https://docs.google.com/spreadsheets/d/1aI3C9f00Dc5OQgIeni8B_rmIaJLcNnrbEfbnb_F-OO0/edit?usp=sharing

A link for each item is included.
This problem seems to be present for some migrated items and others created in Avalon 6:
~123 items migrated
~55 items created after migration

@seanluyk let me know if the number is too large. We could make this change directly in mods although this would require pushing a new version into Fedora production.

**Comment by seanluyk** [comment]
Thanks @anayram this is helpful! Maybe I'm missing something, but I do see some items in this list where the appropriate license appears to have been applied, e.g.

- https://era-av.library.ualberta.ca/media_objects/4x51hj89z
- https://era-av.library.ualberta.ca/media_objects/bv73c167p
- https://era-av.library.ualberta.ca/media_objects/2v23vv589

In any case though, this is a larger list than I expected so I think we have to rule out the manual process for now

**Comment by anayram** [comment]
@seanlyuk - will take a look at the list and get back to you. I generated
it through sold but Mey have to query fedora. Will check with Tai-Chun
about that.

**Comment by anayram** [comment]
@seanluyk : a new report is available [here](https://docs.google.com/spreadsheets/d/1aI3C9f00Dc5OQgIeni8B_rmIaJLcNnrbEfbnb_F-OO0/edit#gid=648193499). The problem includes about 319 cases, so definitely not manual work. I can fix this via mods xml and pass on the cleaned metadata for @jefferya to replace in Fedora if that works for all?

**Comment by seanluyk** [comment]
That works for me, thanks @anayram! I believe @jefferya is also back in the Library starting Monday

**Comment by jefferya** [comment]
Thank you @anayram. 
@seanluyk @mbarnett @anayram, I'm back with UAL for the next 3 weeks.

Can I present an alternative to the approach described above for correcting the records. Points that are uncertain to me:
* if replacing the Fedora descMetadata (MODS) file with a new version, will the Solr index be updated?
*  I'm a bit leery of directly updated Fedora on a production instance

Proposing an alternative (thinking out loud):update via the Ruby/Avalon model
Advantages:
* updates the all necessary data stores (Fedora and Solr) via the same mechanisms as the UI;
* able to run the Ruby/Avalon validation checks against the change and thus report exceptions/problems (e.g., validation as per PR https://github.com/ualbertalib/avalon/pull/341)
* can add a "dry run" that would show the before and after effects
* might require more time but might be more able to safely handle unforeseen problems

Note: a similar code structure could also be used to improve the visibility batch change #596

**Comment by seanluyk** [comment]
Thanks @jefferya and just to confirm - you would like to wait to do this until the 6.5 upgrade is complete, right? This is not a high priority, more of a cleanup thing

**Comment by jefferya** [comment]
Summary of conversation with @anayram 
* Metadata team using the `http` license URLs
* ERA A+V license.yml file contains CC BY 4.0 with a `https` but not others [1]
  * Unable to find a reason for why only one is `https`
  * Also, most MediaObjects use the `http` url (not the `https` url) creating a significant number of invalid MediaObjects

Plan: 
* change the license.yml file [1] to `http` 
* test on uat or staging server
* change the 8 instances by hand once the release deployed to production

[1] https://github.com/ualbertalib/avalon/blob/b7a76fe8381af1b2838f8faf0304a46b95e6b703/config/license.yml#L2

**Comment by jefferya** [comment]
Before change PR #667 (tested on UAT):

```
[18] pry(main)> obj=MediaObject.find('pr76f344p')
[19] pry(main)> obj.terms_of_use
=> "http://creativecommons.org/licenses/by/4.0/"
[20] pry(main)> obj.has_standard_license?
=> false
[21] pry(main)> obj.valid?
=> false
[22] pry(main)> exit
```

After change:
```
[1] pry(main)> obj=MediaObject.find('pr76f344p')
[2] pry(main)> obj.terms_of_use
=> "http://creativecommons.org/licenses/by/4.0/"
[3] pry(main)> obj.valid?
=> true
[4] pry(main)> obj.has_standard_license?
=> true
```
```
