### ISSUE TITLE
Avalon 6.4.5 and 6.5.0 upgrades

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/avalon#587]
We would like to keep our versions as close to upstream as possible.  To do that, we'd like to investigate the work involved to upgrade to 6.4.5 (hotfix) and 6.5.0 (minor version) - Incremental upgrade may or may not be necessary. 

Steps:
- [x] Move `avalon-6` branch to `master` #515
- [x] Create branch `avalon-6.4.5` merge in upstream to tag v6.4.5
- [x] Create branch `avalon-6.5.0` (base branch avalon-6.4.5) merge in upstream to tag v6.5.0 
- [x] Test Travis
- [x] Test Docker (create running Docker Compose) 
    - [x] add to documentation: `DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true RAILS_ENV=test bundle exec rspec` plus setup test.yml for testing
- [x] Apply security updates Gem and Yarn https://github.com/jefferya/avalon/commit/24e98235c16a10cd79bee14397c1ab0d06057b74
- [x] Update UAT
- [x] Test UAT
  - [x] batch ingest (e-mail from Mariana)
  - [x] batch ingest e-mails
  - [x] waveform creation
- [x] Create staging/production install instructions
    - [x] details below on [comment from Feb 28](https://github.com/ualbertalib/avalon/issues/587#issuecomment-592772026)
    - https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.4+to+Avalon+6.5
- [x] Update avalon6-test.library.ualberta.ca and test new features
    - [x] IIIF manifest: `/media_object/${ID}/manifest` https://github.com/avalonmediasystem/avalon/commit/6c4b72e351cbf36762b1756a26c4791b632991ea
    - [x] Timeliner: `/media_object/${ID}` & `timeline` button below media player <https://pawpaw.dlib.indiana.edu/media_objects/2z10wq369/section/bz60cw30w>
    - [x] Structural Metadata Editor: <https://wiki.dlib.indiana.edu/display/VarVideo/Visual+Structural+Metadata+Editor>
    - [x] batch ingest (e-mail from Mariana)
    - [x] batch ingest e-mails
    - [x] waveform creation
    - [x] LTI
    - [x] Shibb

- [x] Deploy to production
  - [x] test
  - [x] check /jobs url to identify failed waveform backfill
- [x] update DI Internal documentation

**Comment by jefferya** [comment]
Context:
* current: 6.4.3 Avalon plus UAL modifications/additions
* investigate upgrade to 6.4.5 (hotfix) and 6.5.0 (minor version) from upstream

Pain points:
* UAL modifications/additions conflict with upstream commits 

Investigation:
* attempted `git merge upstream` 
  * multiple explicit conflicts
  * multiple areas where the automatic merge didn't yield "clean" code

The investigation results likely mean that each Avalon 6.x UAL PR should be reviewed in the context of the upstream changes (i.e., review PRs not individual files) to avoid adding dead code and avoid adding/subtracting code leading to breaking functionality. If the test coverage was higher, then perhaps one could merge each file individually outside the context of a PR but the PR helps identify the purpose of the code change and determine if a particular line is required/necessary   in the context of a merge between UAL and upstream code.

Possible approaches:
1. `git merge upstream` then UAL PR by PR fix the merge
2. start with upstream branch and git cherry pick each UAL PR (then rename branch to master)
    * not sure if this is good practice -- my experiences working with upstream repos is very different than the approach taken by this project.

Uncertainties
* Not certain which is the best approach. 
* Not certain how to make future hot-fixes easier
* The number of changed files doesn't differ significantly from the 6.4.5 (hotfix) to 6.5.0 (minor version)

Mitigating factors:
* not too many PRs/commits on the UAL side. A significant number are easily reconciled with upstream changes. 

Thoughts
* push more UAL changes upstream to reduce the effort required for further hot-fix and minor updates
* can the process be scripted to automate aspects?
* are there alternative code patterns that could be employed to reduce effort?
* would git cherry pick option (#2) allow a scripted way to merge changes in the future?

**Comment by jefferya** [comment]
Consider in conjunction with #515?

**Comment by seanluyk** [comment]
Just thinking about this and wondering how difficult it would be to identify which of our changes relate to any specific functionality and if that functionality is absolutely necessary to carry forward or not? Some definitely is (e.g. SAML integration), but perhaps some others are not (e.g. customizations to the resource description form) IMO

**Comment by jefferya** [comment]
[ ] Test: db:migrate failed with local version of MySQL; commit referenced will fix in tests but will the fix a cause problem with production data: 65f5e74b9e24edd8b2ae1d1dd2db18e41b0a3e90

**Comment by jefferya** [comment]
> Just thinking about this and wondering how difficult it would be to identify which of our changes relate to any specific functionality and if that functionality is absolutely necessary to carry forward or not? Some definitely is (e.g. SAML integration), but perhaps some others are not (e.g. customizations to the resource description form) IMO

These are some that come to mind that have made pulling in upstream changes harder:
* these commits around matterhorn, working directory, and how secrets.yml is used: #283, #396, #379, #454
* to a lesser extent, unpublish #352 

UAL customisations that are well documented and change only small, easily understood pieces are easier to reconcile with upstream (e.g., resource description, SAML) in the context of the 6.4 and 6.5 updates.

I could gather a full list with opinions based on my experience with v6.4.5 and v6.5.0 updates.

Personally, I wonder if contributing more changes on the UAL side to upstream (where it makes sense, e.g., #592, and others) would make future updates easier.

**Comment by seanluyk** [comment]
Thanks, @jefferya this is helpful info for me to know. 

Re #352 this is one customization that upon reflection, I think we could give up if it makes future upgrades a bit smoother. We've found that other areas of the Avalon permissions model necessitate us giving manager level permissions anyway, and this is limited to a select group so it's no big deal.

Whatever works best for your process, and for making future updates smoother, I'm in favour of!

**Comment by jefferya** [comment]
Investigate:
- [ ] ActiveRecord::NotNullViolation (Mysql2::Error: Field 'clip_id' doesn't have a default value: INSERT INTO `playlist_items` (`playlist_id`, `position`, `created_at`, `updated_at`) VALUES (17, 2, '2020-02-06 22:59:42', '2020-02-06 22:59:42')):
    - maybe related to playlist
- [ ] e-mail notifications

**Comment by jefferya** [comment]
Draft upgrade install instructions:
- Details <https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.4+to+Avalon+6.5>
  - UAL specifics
    - Node.js version (tried v13 but it failed) indiana.edu say tested with v10 - ToDo: is v10 too old and a security risk? Note: also modify .travis `nvm install 8` for tests
    - instead of altering `settings.yml` in the indiana.edu instructions, add to the UAL setup for Apache and sysconf the following env var: `SETTINGS__TIMELINER__TIMELINER_URL=http://localhost:3000/timeliner`
      - add to env documentation; add to release notes.
    - db migration: adds timeline table and update Rails 4 to Rails 5.1 automatically generated primary key and foreign keys to bigint as per https://github.com/jefferya/avalon/commit/dc5b56754b4c01b7be67d8caac57a2661471381e
