### ISSUE TITLE
editor role is not working properly

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#60]
### Descriptive summary

When we assign someone as an editor, the user is not able to make changes in the metadata

### Expected behavior
A user assigned with "editor" role for a particular collection should be able to make changes to metadata.

### Actual behavior
Currently an "editor" is not able to make metadata changes and save them. To overcome this, we have been assigning "manager" role which give them more power than we would like.

### Related work

#61

**Comment by cwant** [comment]
Hi Sean, I'm not about to replicate this. For example, on the test server I have a collection called "Chris Stuff" and I have added cjwant@gmail.com as an editor. When I create an account for cjwant@gmail.com and log in, I am able to locate the collection and update the metadata.

Could you please outline the steps to replicate this problem?

**Comment by seanluyk** [comment]
Hi @cwant, in production, here are the steps to replicate this issue:

1. Go to manage content>Sandbox collection
2. Add a CCID holder w/o admin or manager permissions as an editor
3. See if they can add/edit metadata on an object in that collection (they won't be able to, I suspect)

If it's working on test I wonder if it has something to do with the fact it's a CCID?

**Comment by cwant** [comment]
I think I am able to replicate this in the test stack with a non-CCID user (good thing too, this will make it easier to debug). In the example I provided above, I was able to edit two items in the collections, but there are two others that won't allow editing -- pretty weird!

**Comment by cwant** [comment]
This is what I have discovered: an editor can edit an item in a collection until it is published. Published items can not be edited by people with the edit permission.

**Comment by cwant** [comment]
Just to confirm: if an admin presses "unpublish" for an item, the editor can now modify the metadata.

A decision should be made whether this is the behaviour we want, or whether we want editors to be able to edit published items too.

**Comment by seanluyk** [comment]
@cwant, thanks for your investigation into this. To answer your questions, I would like the roles to work exactly as specified in the documentation (roles table) for now. Once we've got experience using them with end users we can consider adjusting. I can't recall if an editor can't edit a published item, but if that's the stock behavior I'm good with it!

**Comment by seanluyk** [comment]
@cwant confirmed with user that she is not able to assign access (or use any edit functions) with editor role assigned. Here is the object: https://era-av.library.ualberta.ca/media_objects/avalon:1163

User has been assigned editor role on manage collection page: https://era-av.library.ualberta.ca/admin/collections/avalon:1151

**Comment by cwant** [comment]
Hi Sean, as mentioned earlier in this ticket, Avalon will not allow editors to edit published items. The items in that collection have been published.

According to the Avalon permissions matrix in their documentation, editors aren't allowed to edit published objects, so if you want our Avalon to work exactly as the documentation states, it is currently doing it (in which case, if you want to grant edit access to the user, you need to unpublish first).

If you want to deviate from the documentation, there are a number of options (let editors edit published items, allow editors to unpublish items so they can work on them, etc.)

**Comment by seanluyk** [comment]
Reopening as a user reported that they are unable to unpublish an item and are receiving some interesting errors. When the user tries to unpublish an item, they get the following errors:
![image](https://user-images.githubusercontent.com/14880206/29182919-fb590298-7dbd-11e7-9c69-5592754e4bdf.png)

This is preventing them from being able to assign special access. I'm going to meet with them at 10 AM tomorrow to see the issues in action. Maybe @cwant and @umarqasim could join?

**Comment by umarqasim** [comment]
@seanluyk, I can join at 10 AM tomorrow.

**Comment by cwant** [comment]
I can likely join (I have a 10:30 meeting that will very likely be cancelled).
