### ISSUE TITLE
Update UAL Logo

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#635]
**Is your feature request related to a problem? Please describe.**
With the recent name change from Libraries to Library, we should update the header logo accordingly

**Describe the solution you'd like**
Update logo in the header to the new University of Alberta Library logo, available from the [Media Toolkit](https://www.ualberta.ca/toolkit/downloads/logos)

**Comment by jefferya** [comment]
@seanluyk 
- updated logo
- also updated text in on the site (e.g., homepage blurb, about ERA A+V, technology and partnerships page): see https://github.com/ualbertalib/avalon/pull/655/files for details. Would like second set of eyes to verify correctness

![Screenshot_2020-07-03 Avalon Media System(1)](https://user-images.githubusercontent.com/879785/86497984-0acdba00-bd41-11ea-85d2-8fe9906cf435.png)

**Comment by seanluyk** [comment]
Thanks @jefferya!
