### ISSUE TITLE
Manage Files - Relabel Associated Files to Uploaded Files

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#64]
### Descriptive summary

On manage file(s) form relabel "Associated Files" to "Uploaded Files": 
![image](https://cloud.githubusercontent.com/assets/14880206/22611529/4d91f44a-ea28-11e6-9605-1d36cc56d219.png)

**Comment by cwant** [comment]
The same page is used both a) during initial upload, and b) during edit of the item later. In that second situation, the term 'Uploaded Files' may not be entirely appropriate if no files were uploaded during the editing session.

**Comment by umarqasim** [comment]
If no files have been uploaded, may be we display a message underneath, something like "No uploaded files found"

**Comment by seanluyk** [comment]
Prior to upload the page looks like this and maintains that state until files are uploaded:
![image](https://cloud.githubusercontent.com/assets/14880206/22712148/f4eb75c0-ed40-11e6-8258-754e29753e43.png)
To be more specific, this issue is about the page that appears during edit of item later, which looks like this: 
![image](https://cloud.githubusercontent.com/assets/14880206/22712184/16d579c4-ed41-11e6-8b43-d3607638e0c8.png)

**Comment by seanluyk** [comment]
Doing some cleanup
