### ISSUE TITLE
Relabel LTI URL tab and text

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#66]
### Descriptive summary

PROD - when a logged in user views share options, there is an LTI URL tab and explanatory text that is not easily understandable by non-technical users 

### Expected behavior
-LTI URL tab should be relabelled to "eClass"
-Text in this tab should read: "Copy the link below to share this resource in eClass or other learning management systems"

### Steps to reproduce the behavior

1. As a logged in user, go to any record view
1. Click share and go to LTI URL tab

**Comment by cwant** [comment]
@seanluyk Any interest in making the 'eClass' panel the default shown when clicking share? It is currently set to 'Share this resource' (which provides regular URLs to Item/Section), which semantically makes more sense, but if the primary reason why we have the share link is to embed videos in eClass, it might be worth saving the user an additional click. (There are pros and cons for either way.)

**Comment by seanluyk** [comment]
@cwant I'd say that it's a toss up, so maybe we just leave it for now? Aside from the video games MOOC, we don't have any other active use cases for the eClass links, so it is currently more common to use the share this resource links
