### ISSUE TITLE
Exposed closing span tag in facet popup windows

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#664]
A closing span tag is appearing in facet popup windows, see below:
![Screen Shot 2020-08-16 at 12 54 18](https://user-images.githubusercontent.com/14880206/90341784-b95f4e80-dfbf-11ea-832b-6acf7196311d.png)

To reproduce:
1. Browse ERA A+V
2. Click on the more button for any facet
3. Note exposed tag

**Comment by pgwillia** [comment]
This same problem was in Discovery and NEOSDiscovery.  Turns out this is a known problem and fixed in a 6.x version of Blacklight. If you're not able to bump the version, this is what I was able to do for Discovery: https://github.com/ualbertalib/discovery/pull/2032/

**Comment by jefferya** [comment]
@pgwillia Is the code snippet referenced above in Discovery an extension of Blacklight? 

Took a quick look at the Avalon codebase to see if this would be a easy fix. Didn't find an easy thread to pull (e..g, https://github.com/ualbertalib/discovery/pull/2032).

Todo: check upstream and see if affected. If fixed, cherrypick code.

Avalon v6.5 is on a v6.20.0 of Blacklight: https://github.com/ualbertalib/avalon/blob/master/Gemfile.lock#L253

**Comment by pgwillia** [comment]
> 
> 
> @pgwillia Is the code snippet referenced above in Discovery an extension of Blacklight?
> 
> Took a quick look at the Avalon codebase to see if this would be a easy fix. Didn't find an easy thread to pull (e..g, [ualbertalib/discovery#2032](https://github.com/ualbertalib/discovery/pull/2032)).
> 
> Todo: check upstream and see if affected. If fixed, cherrypick code.
> 
> Avalon v6.5 is on a v6.20.0 of Blacklight: https://github.com/ualbertalib/avalon/blob/master/Gemfile.lock#L253

https://github.com/ualbertalib/discovery/issues/2011#issuecomment-662278716 

It was fixed in 6.23.0 release https://github.com/projectblacklight/blacklight/issues/2247

**Comment by jefferya** [comment]
Trying `bundle update blacklight --conservative` which bumps to Blacklight 6.24.0. A quick scan of the commits between 6.20.0 and 6.24.0 look ok, running tests and need to look into the commits in more details: <https://github.com/avalonmediasystem/avalon/pull/4335/files>

The alternative option is: <https://github.com/avalonmediasystem/avalon/pull/4335/files>

**Comment by jefferya** [comment]
Addressed in release: v6.5.0.20210322.uofa
