### ISSUE TITLE
Revision to text on policies page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#670]
Due to a recent policy change, a line of text on https://era-av.library.ualberta.ca/policies needs to be changed:

- Under Content Policy, please change the first bullet text from "Commercial audio and video files used for instructional purposes, such as course reserves accessed by students through eClass or items streamed for classroom viewing" to "Course materials, such as audio and video files that need to be streamed for classroom viewing. Contact us for more information about copyright restrictions and the purchase of streaming rights."

**Comment by jefferya** [comment]
![Screenshot from 2020-10-30 10-43-58](https://user-images.githubusercontent.com/879785/97733028-eab6c900-1a9c-11eb-9823-c3a3d1cae41f.png)
