### ISSUE TITLE
Waveform editor not working correctly

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#680]
##To replicate##
- Go to [this item] (https://era-av.library.ualberta.ca/media_objects/6t053g96s)
- Click edit, structure, +structure, edit structure
- Attempt to edit an entry (pencil icon)

The window closes and no edits are allowed. May be item-specific so I'm wondering if this one of the items where the backfill script failed?

**Comment by jefferya** [comment]
Tested on Ubuntu 18.04 / Firefox 82.0.3. Able to reproduce.

According to Firefox console, there is a JavaScript exception causing the window to close. 

Todo: try to reproduce in a dev environment. 

Hypothesis, there might be an invalid number in one of the time spans, will check.
`Uncaught TypeError: peaks.segments.add(): startTime should be a valid number`

![Screenshot from 2020-11-12 15-10-41](https://user-images.githubusercontent.com/879785/99002168-45b6da00-24f9-11eb-8452-e685b80c665d.png)

**Comment by jefferya** [comment]
@seanluyk 

Summary of what I've found: if the start time and end time are the same exact time then the structural editor with the waveform fails. For example 
`<Span label="Sparshott reads “Untitled”" begin="00:00:10.00" end="00:00:10.00"/>`. 

Questions:
* Is setting the begin and end to the same point in time intentional (and have meaning) or a data entry error?
* The structural editor (with waveform) will not allow the begin and end to be the same time point. Will this be a problem from the service side?

Details:

I'm able to reproduce in the following manner. 
* Go to item
* Click edit, structure, +structure, advanced edit 
* add timeline span with start/end at same point in time (e..g, "00:00:10.00")
* save and close
* refresh page
* edit structure (the visual time view)
* attempt to edit an entry (pencil icon)

The window closes and no edits are allowed.

**Comment by seanluyk** [comment]
Thanks for your investigation @jefferya, I believe these are data entry errors, and that they explain why the waveform editor is not working properly. I'll explain this to the users and let you know if any other issues come up!

**Comment by seanluyk** [comment]
Just took a look at the XML and something weird is going on. If you compare the XML that appears in the source file used for batch ingest of this item with what is now appearing in the advanced structural editor, you'll see some differences:

*Original Source XML in Dropbox*
<Div label="Francis Sparshott"><Span label="Birney introduces Francis Sparshott" end="0:09:14" begin="0:09:06"/><Span label="Sparshott introduces and reads “Wasp Winter”" end="0:09:56" begin="0:09:15"/><Span label="Sparshott reads “Dream Poem”" end="0:10:24" begin="0:09:59"/><Span label="Sparshott reads “Untitled”" end="0:10:52" begin="0:10:25"/></Div>

*What appears in the advanced editor*
<Div label="Francis Sparshott">
        <Span label="Birney introduces Francis Sparshott" begin="00:00:09.00" end="00:00:09.00"/>
        <Span label="Sparshott introduces and reads “Wasp Winter”" begin="00:00:09.00" end="00:00:09.00"/>
        <Span label="Sparshott reads “Dream Poem”" begin="00:00:09.00" end="00:00:10.00"/>
        <Span label="Sparshott reads “Untitled”" begin="00:00:10.00" end="00:00:10.00"/>
    </Div>

The spans seem to have been transformed during the ingest process

**Comment by seanluyk** [comment]
@jefferya just to add to this discussion, we're getting these kinds of errors not just with legacy items (i.e. those created prior to the Avalon upgrade) but also with newly created ones, e.g. https://era-av.library.ualberta.ca/media_objects/c821gm09w

In this case, it's not possible to edit the final timestamp properly and add more

**Comment by jefferya** [comment]
@seanluyk I've done a superficial investigation.My hypothesis is the input validation for the structural components, in the past, may have missed certain scenarios (e.g., Dec 1st comment) and allowed the input but today, with the current v6.5 Avalon, the input triggers failures. I need to test this more fully.   The `6t053g96s` example needs a bit more investigation on my end (a hypothesis below)


* c821gm09w: 

Details:

Regarding <https://era-av.library.ualberta.ca/media_objects/c821gm09w>, there's something weird. The last span has an end point of `01:64:0-3586.54` and the Avalon may be having a problem with the time format (I don't recognize the format). The JSON input to the waveform structure editor is the following <https://era-av.library.ualberta.ca/master_files/x059c857c/structure.json>:
```
{"type":"span","label":"Jones performs \"At Ease in Order or In Ruins…”","begin":"00:59:52.40","end":"NaN:NaN:NaN"}
```

Regarding 6t053g96s (above), could the the missing `00` in the input (e.g., `0:09:06`) be the problem?

**Comment by seanluyk** [comment]
@jefferya that weird last span seems to be what Avalon is adding. Even if you try to create an end span that's 1 ms after the begin span, it doesn't let you update it. We've noticed that spans in the new editor tend to be problematic at the end of a recording, so I'm not sure if that's significant. Also of note in c821gm09w is that no XML appears in the "advanced editor". With other problems like these, we've been able to fix them by changing the spans there. Not sure if the XML is supposed to populate from entry in the waveform editor or not?

**Comment by jefferya** [comment]
@seanluyk clarification, when the structural metadata is added, is it added via the UI (i.e., the waveform editor or the advanced editor)? Or can the structural metadata be added via a batch ingest? Also, is the "upload" UI element used to attach structural metadata? The questions aim to help understand which approaches are used to add structural metadata and which I should focus on when testing.

Second question, is there some preexisting documentation for ERA A+V that outlines the steps to add structural metadata? I'd like my tests to as much as possible follow what that of others. However, if the nothing written exists, I'll follow the direction the UI intuitively takes be based on examples.

c821gm09w: is there an urgent need? There might be way to fix the time via the api as I suspect the problematic time is causing the UI problems (assuming the structural metadata wasn't added via the upload button).

**Comment by anayram** [comment]
Structural metadata can be added via the UI and also via batch ingest.

**Comment by anayram** [comment]
Sorry, I sent before completing the message. Structural metadata can be added via the UI and also via batch ingest.

We don't have specific instructions for adding structure metadata for ERA A+V but here are the documentation pages we use: 

1. [Adding Structure to Files Using the Graphical XML Editor](https://wiki.dlib.indiana.edu/display/VarVideo/Adding+Structure+to+Files+Using+the+Graphical+XML+Editor
)

1. [Visual Structural Metadata Editor](https://wiki.dlib.indiana.edu/display/VarVideo/Visual+Structural+Metadata+Editor
)

1. [Adding structure via batch](https://wiki.dlib.indiana.edu/display/VarVideo/Batch+Ingest+Package+Format#BatchIngestPackageFormat-Addingstructurefilesviabatch)

**Comment by jefferya** [comment]
@anayram very helpful, thank you. 

For testing batch ingest with structural metadata, is there an item in dropbox or google drive that you can point me to as I'd like to grab the batch ingest plus structural metadata file to use for local testing. No rush.

**Comment by anayram** [comment]
@jefferya no problem, here are the test files I use: https://drive.google.com/drive/u/0/folders/1_knq9iHuJqitilTOCnhHFRxEVcUSuMOS

Use the files highlighted here:
![image](https://user-images.githubusercontent.com/879749/101533349-f37ba400-3952-11eb-81ec-b8b1cdf45ba0.png)

**Comment by seanluyk** [comment]
@jefferya we've experienced issues with both structural metadata added via batch and newly created metadata in the UI using the waveform editor. I don't believe we've had many issues when using the advanced editor

**Comment by jefferya** [comment]
Note: 
* Look upstream for code fixes: <https://www.avalonmediasystem.org/avalon-features-latest-release>. Note, v7.1.1 `Updated the Structural Metadata Editor in Avalon with fixes and dependency upgrades`

**Comment by seanluyk** [comment]
Here are two items where the waveform editor is causing issues:

SW039a1 - (it is listed in ERA-AV as SW039a) https://era-av.library.ualberta.ca/media_objects/c821gm09w
SW050b2 - (it is listed in ERA-AV as SW050a) https://era-av.library.ualberta.ca/media_objects/j9602160s

"once I get up to about the 59 minute mark, the autofilled end times and start times begin corrupting to 01:64:0-3586.54"

**Comment by jefferya** [comment]
Able to reproduce
* upload and ingest SW039-a-cleaned.wav
* add structure via advanced structural metadata editor
* add first timespan: timespan ranges from 0 to 59min
* add second timespan: timespan autofill range from 59 to a weird timestamp

Tried with upstream version v7.1.1 (test if updated structural metadata editor (SME) JS code fixes problem)
* add structure 
* add first timespan: default range
* error occurs (different from local version)

Try update v7.2 (test if updated structural metadata editor JS code fixes problem)
* SME updates in v7.2 seem to fix problem; will try pulling in the latest upstream JS code into local v6.5 codebase

**Comment by seanluyk** [comment]
That's excellent news, Jeff. I'm hoping that this fixes the issue! Let me know if I can help with any testing

**Comment by jefferya** [comment]
Diagnostics:

* structuralMetadataUtils.toHHmmss(3643.35): "01:60:0-3556.55"

Problematic code:

https://github.com/avalonmediasystem/react-structural-metadata-editor/blame/82a4b6b36406ae117fcf00f70ce9660df07fa2a1/src/services/StructuralMetadataUtils.js#L829

Upstream fixed by:

https://github.com/avalonmediasystem/react-structural-metadata-editor/blame/master/src/services/StructuralMetadataUtils.js#L838


Tried using the following commit:

https://github.com/avalonmediasystem/react-structural-metadata-editor#9e9527eb4c5ae2f17a69441e61955743cb0d5117

> Uncaught TypeError: nextProps.structureIsSaved is not a function

**Comment by jefferya** [comment]
# End time bug (3643.35 seconds not properly converted to HH:MM:SS.ss):
![Screenshot from 2021-01-26 16-36-46](https://user-images.githubusercontent.com/879785/105920804-36720380-5ff5-11eb-8238-c40c34e3e048.png)


# After React Structural Metadata Editor update with properly converted end time
![Screenshot from 2021-01-26 16-26-11](https://user-images.githubusercontent.com/879785/105920808-370a9a00-5ff5-11eb-93d4-7cd5a6858a31.png)

* updates React Structural Metadata Editor (SME) to the latest version
  * https://github.com/avalonmediasystem/react-structural-metadata-editor#9e9527eb4c5ae2f17a69441e61955743cb0d5117
* update Ruby connector to support updated (SME): 
  * unsaved change handling: cherry-pick files but leave yarn.lock: https://github.com/avalonmediasystem/avalon/commit/3d569fb2a3b4d5be2b1f040db9abacd53f8a8988

**Comment by jefferya** [comment]
@seanluyk @anayram 
To repair the problematic structural metadata produced by the Structural Metadata Editor (SME) in upstream v6.5
* click `Edit` on each timespan with an end-time beyond the 1hr mark, adjust end-time mark (if needed), and save timespan
* save structure
* reload page
* check SME
* check advanced edit (if raw xml view doesn't contain the timespan then there remains a problematic timespan)

Notes:
* To check if the structural metadata is problematic: check the `advanced edit ==> raw xml` view and if the view lacks timespan structure then structural metadata is problematic
* Validation of timestamps is very weak, for example, if metadata added via `raw XML` form as `01:01:61.000` (note: 61 sec) then no error is triggered. If viewed by SME, the time mark is displayed as `01:01:01.000` and saved as such (truncating 61 sec to 1 sec). Also, the media player when used with associated structural metadata does understand 61 sec.

**Comment by seanluyk** [comment]
@jefferya I just did some testing and I'm not sure if this is completely fixed? I was able to add a new timespan to the SpokenWeb example in the object you shared with us, however, the changes don't appear in the advanced (XML) view

**Comment by jefferya** [comment]
Sean and I met and verified the changes fix the problem.
