### ISSUE TITLE
Player controls invisible

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#684]
Player controls are no longer visible, for example:

![image](https://user-images.githubusercontent.com/14880206/100269666-20bc6100-2f14-11eb-98db-0a6d60dba0c3.png)

MacOS 11, Chrome, Firefox, Safari

**Comment by jefferya** [comment]
I don't have access to a MacOS 11 computer. I've tried to reproduce but have been unsuccessful on live.browserstack.com, a site that allows live, interactive browser testing using MacOS Big Sur on the following:
* Safari 14 
* Firefox 84 
* Chrome 88 

@seanluyk: are you able to test on MacOS 11? If so, could we test on an recently updated browser? 
* https://era-av.library.ualberta.ca/media_objects/1g05fc15t

**Comment by seanluyk** [comment]
@jefferya Just tested in OS 11 using all these versions of browsers, and am no longer experiencing the issue
