### ISSUE TITLE
Resource Description Page - agreement in wrong stage of workflow and must be accepted each time metadata is edited

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#69]
### Descriptive summary
The user agreement is the last metadata field on the resource description page and users must click "I agree" before saving changes. However, each time an edit is made on the resource description page, users must click "I agree".  Also, the user agreement is placed in the wrong stage of the deposit workflow; the agreement relates to content uploaded, not metadata added.

### Expected behaviour
-User agreement is on the manage file(s) page
-Users agree once/file uploaded on the manage file(s) page and their answer is locked and recorded

### Actual behaviour
-User agreement is last field on resource description page
-Subsequent edits to metadata require agreeing again and answer is not locked/saved

### Steps to reproduce the behavior

1. Edit metadata for any object. Note that I agree is off. Click I agree and save and continue
1. Edit metadata again to reproduce issue

**Comment by seanluyk** [comment]
This one will need some more discussion, I think. I'm not convinced that the user agreement applies to our mediated deposit environment and potential use of in-copyright materials in the repository (i.e. it's a UAL staff member agreeing to deposit terms that don't apply to them because they do not own the content)

**Comment by umarqasim** [comment]
A similar process is being used in ERA for any mediated deposit case. We should chat with @leahvanderjagt about this.

**Comment by seanluyk** [comment]
Doing some cleanup
