### ISSUE TITLE
High resolution stream fails to load

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#695]
Reported by a user:

-For [this item](https://era-av-library-ualberta-ca.login.ezproxy.library.ualberta.ca/media_objects/f4752h78g), selecting the high-resolution derivative does not load.

**Comment by jefferya** [comment]
@seanluyk Sent e-mail to the ERA A+V team with diagnosis. 

Synopsis:
* reproducible via EZProxy
* functions error free when not using EZProxy

**Comment by jefferya** [comment]
workaround in e-mail conversation
