### ISSUE TITLE
Waveform creation fails if apostrophe in collection name or media file name

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/avalon#714]
Descriptive summary

Either ingest an item into a collection with a name containing a apostrophe (e..g, Nature's Laws) or ingest a media file with a name containing an apostrophe (e.g., 02 Here's Two.m4a) causes the waveform creation to fail.

Expected behavior

Structural Metadata Editor opens the waveform or the API endpoint http://localhost:3000/master_files/0g354f20t/waveform.json returns the waveform data

Actual behavior

404 error due to waveform not existing

Steps to reproduce the behaviour

1. upload a media file with an apostrophe in the name
2. check the Structural Metadata Editor (edit=>structure=>edit structure

**Comment by seanluyk** [comment]
Very interesting. An apostrophe in a collection name is going to be rare, and we can not use them in file names. Good catch!

**Comment by anayram** [comment]
Wow, good catch @jefferya !
