### ISSUE TITLE
Add a License column linked to the "License" metadata field in batch ingest script

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#73]
### Descriptive summary

There is no "batch ingest" column for "License" field. All license related information is going to the "Terms of Use" field. Need to fix this

### Expected behavior
Need a column for  adding "License" in the batch ingest manifest.

### Actual behavior
Currently "Terms of use" column is being used to enter license information but this metadata field is not linked to  license field. For this reason, after ingestion, license text appears in the "Terms of Use". 
### Steps to reproduce the behavior
See any item in Manning Collection
Also check sample [batch ingest manifest template](https://wiki.dlib.indiana.edu/display/VarVideo/Batch+Ingest+Package+Format)

### Related work
#58

**Comment by seanluyk** [comment]
Should be solved by #98 because terms of use is in batch ingest script. Closing for now.
