### ISSUE TITLE
Moodle LTI Plugin for Avalon

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/avalon#77]
### Descriptive summary
Currently eClass moodle instance provide an "external Tool" plugin to link an AV object from eclass to ERA A+V via LTI. We would like a separate plugin in Moodle specifically developed and customized for ERA A+V connection with default settings making it easier for instructors to fill in the details for LTI integration.
![image](https://cloud.githubusercontent.com/assets/2874660/23086657/8c921e28-f52b-11e6-9bc8-8fa9cbbd511e.png)

### Expected behavior
Similar to "External Tool" but with pre-filled fields and making only related fields visible

### Related work

Link to related tickets or prior related work here.

**Comment by seanluyk** [comment]
Sean, @umarqasim and @weiweishi to contact eClass team to start discussing this

**Comment by seanluyk** [comment]
Doing some cleanup
