### ISSUE TITLE
Avalon Resource Description Page Changes: Subject

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/avalon#78]
The resource description page should allow users to add subject terms according to type: 
topical, spatial, temporal, and named entity (e.g., person, organization, etc.). 

Multiple values should be allowed. 

One subject of any type should be required.

- [ ] text box for users to enter a term
- [ ] dropdown menu to assign a type to each term
- [ ] user-friendly labels for types

Mappings to MODS:

topical: \<subject>\<topic>
spatial: \<subject>\<geographic>
temporal: \<subject>\<temporal>
named entity: \<subject>\<name>

Part of epic ualbertalib/avalon#51

**Comment by seanluyk** [comment]
@sfarnel should this be controlled in any way/built from LCSH?

**Comment by seanluyk** [comment]
@zschoenb to investigate applicability of FAST

**Comment by seanluyk** [comment]
Doing some cleanup
