### ISSUE TITLE
Batch Ingest script changes: batch update

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/avalon#80]
When we start ingesting, the url is not available if the related item is in the same manifest.

Options:
- Ingest fake dummy related item urls
- Make the url field optional
- Make predictable urls before ingest based on an ID (does this contradict opaque naming used elsewhere in Hydra)
- Can we create a batch update script to make batch changes to existing metadata.

Questions for @umarqasim & @seanluyk 

- Should batch ingest be its own issue (i.e. is this happening anyway?)?
- If so, should batch ingest also produce some kind of audit to assist batch update (ie. a list of ingested URIs)?

Part of epic https://github.com/ualbertalib/avalon/issues/52

**Comment by seanluyk** [comment]
This one is also in #39

**Comment by cwant** [comment]
Thinking this through: do we want to just update metadata via batch, or do we also want to update the master files via batch? (First part is likely easy, second part might be more tricky)

**Comment by seanluyk** [comment]
Good question @cwant. I hadn't thought about the possibility of doing batch master file updates, but that would be very useful. For example, with the Gouglas videos, we need to re-ingest the videos and transcode them this time but the metadata is OK IMO. This is not a high priority as we can always just redo the whole group using the regular batch ingest process, but worth investigating

**Comment by cwant** [comment]
Hi all,

I've supplied some documentation for this nascent feature:

https://github.com/ualbertalib/avalon/wiki/Batch-Update

Please check that this matches your understanding of how the feature should work.

**Comment by seanluyk** [comment]
Looks great, @cwant  - this matches my understanding of this feature. One question - is there an easy way to get a report of object ids for a collection as needed? I think we discussed this at a grooming meeting but I'm not sure where it went.

**Comment by cwant** [comment]
Hi @seanluyk, sorry for the slow reply. Define "easy" ...? It's not particularly difficult, it just takes time to spec out the work needed and produce a report, e.g.,

* Do you want an "export to CSV" option for a collection?
* Or JSON format?
* Or do you want the report to just be a webpage?
* Or all of the above?
* What additional information do you want for each record?
* All descriptive metadata?
* Data about the master files or derivatives?

This work should be scoped out in a separate ticket.

**Comment by seanluyk** [comment]
Scoped out this work in #134
