### ISSUE TITLE
Batch Ingest script changes: Contributor role

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/avalon#81]
Batch ingest needs to accommodate multiple roles for contributors.

Related to issue https://github.com/ualbertalib/avalon/issues/79 discussing contributor role changes in the interface.

Related to issue https://github.com/ualbertalib/avalon/issues/29 especially final comments by @anayram 

Examples provided by @anayram in issue #29 are available in the following documents:

- Test objects with new fields (includes manifest, structure files, and video file) available at:
https://drive.google.com/drive/u/0/folders/0B-wPdqHEduXteTZqeDNlSkYzUU0

- Metadata available in manifest spreadsheet's sample_obj_new_fields tab:
https://docs.google.com/spreadsheets/d/1vCiyWzmYkrf7vqHFb-e97cGv3W0yZrEWr2Icjc9X2BM/edit#gid=1545182539

Part of epic #52

**Comment by weiweishi** [comment]
will work on this as part of #84

**Comment by seanluyk** [comment]
Doing some cleanup
