### ISSUE TITLE
Batch Ingest Z39.50 testing with Bibliographic ID

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/avalon#82]
System chokes on Bibliographic ID at ingest.

Somewhat related to adding z39.50 support in item #13 

Part of epic #52

**Comment by weiweishi** [comment]
We will test again with the Z39.50 in place to verify if it's still the case.

**Comment by cwant** [comment]
I have tested (on my development server) that adding the Bibliographic ID to the manifest spreadsheet imports the item successfully.
