### ISSUE TITLE
Agreement checkbox

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/avalon#85]
Investigate the rights agreement checkbox workflow.

Questions for @umarqasim & @seanluyk & @sfarnel 

- Should the checking of the agreement checkbox be stored, or simply a matter of submission workflow?
- How is this handled in ERA? Should Avalon follow suit.

Part of epic #52

**Comment by seanluyk** [comment]
To answer your questions:

- Should the checking of the agreement checkbox be stored, or simply a matter of submission workflow?
>This should be stored, and ideally, we need to store consent of the agreement for each subsequent file added 
- How is this handled in ERA? Should Avalon follow suit. 
>A future ERA A+V enhancement would be to mirror the approach in ERA, where the deposit acceptance is a separate step in the workflow from resource description. It would work differently in ERA A+V simply because of the multi-part file issue

**Comment by umarqasim** [comment]
This needs to be discussed in view of our overall policy of recording or keeping track of who agreed to the term and conditions. It is not attached to batch-ingest so making it a post-launch task with medium priority.

**Comment by seanluyk** [comment]
Doing some cleanup
