### ISSUE TITLE
Avalon batch ingest script changes: Topical Subject & Language (should be required)

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/avalon#86]
Topical subject and language are required fields in the interface. They are not currently (but should be) enforced in the batch ingest. 

Add topical subject and language requirements to ingest validation.

Part of epic #52

**Comment by umarqasim** [comment]
@cwant will investigate if this is already in place

**Comment by cwant** [comment]
This is the case, and I've added some automated tests to the test suite to confirm, so this issue can be closed.
