### ISSUE TITLE
Dates should be selected in resource description page with date picker

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#87]
All date fields in resource description page should allow the use of a date picker that allows a user to enter the minimum (YYYY) or maximum (YYYY-MM-DD) amount of date information. This should allow a user to just be able to enter YYYY and leave MM-DD blank.

**Comment by cwant** [comment]
Hi Sean, do you have an example of a date picker on a web page (somewhere on the net) that exhibits the exact behaviour you want?

**Comment by seanluyk** [comment]
Let me have a look

**Comment by seanluyk** [comment]
@sfarnel @sfbetz  - any ideas on where we could find a date picker that does this.  I think Sonya mentioned that there was something in the works in the Sufia project to deal with this? I;'ve not been able to locate a datepicker that does this

**Comment by cwant** [comment]
I did take a look around and didn't come up with much. Probably have to do something like this:

https://jsfiddle.net/cwant/dktcvpg8/2/

(Text box for year, date picker for date.)

One issue though is that the year range can be restrictive for a date picker. E.g., if you are ingesting digitized content from 1973, likely the years on the date picker won't go there. The date picker that comes from jQuery (in the above link) allows you to type in a new year that overrides the pull down (updates the calendar too, putting the year you typed in the middle of a 20 year range in the pulldown).

**Comment by sfbetz** [comment]
I think something that looks like this should work. I would present in the order of year, month, date, and have the year filled in with current year, and then leave the month and date blank, forcing user to only enter when they need them. http://vitalets.github.io/combodate/

**Comment by seanluyk** [comment]
Thanks @cwant and @sfbetz  - both options look good and I like how Sonya laid out the options - we want year to be mandatory but sometimes we'll have more. This would be a good one to test with various scenarios (batch, Z39.50, user input) to make sure we've got it.

**Comment by seanluyk** [comment]
Doing some cleanup
