### ISSUE TITLE
Poor playback performance with high quality videos

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#93]
### Descriptive summary
High quality videos (MP4s, transcoding skipped) in ERA A+V PROD do not stream well when not connected to UAL ethernet (e.g. from UWS).  Skipping through a video produces jagged playback and out of sync audio. I verified this on one of the brand new Windows loaner laptops in Rutherford on UWS.  

### Expected behavior
High quality videos stream well outside of UAL ethernet.
 
### Actual behavior
Performance/quality suffers significantly on non-UAL ethernet connections with non-transcoded high quality videos

### Steps to reproduce the behavior

1. View the following video on UWS: https://era-av.library.ualberta.ca/media_objects/avalon:975
1. Skip to different sections in the video, pause/play, etc.

**Comment by cwant** [comment]
Googlas' videos aren't trancoded. Likely we will want to do this.

**Comment by cwant** [comment]
Question: what constitutes good enough? UWS performance is important.

Actions:

* Check documentation, and investigate;
* Config for streaming server and transcoding server could be looked at.;
* Check with avalon slack channel if others have this problem.

Treat this as a spike, time box five hours.

**Comment by seanluyk** [comment]
Doing some cleanup
