### ISSUE TITLE
Resource Description Page - make required fields more visible

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#94]
Indicate required fields as is done in ERA:

1. Red asterisk (slightly larger than field name text) preceding required field name 

1. Under Resource Description title, replace Fields followed by an asterisk (*) are required. with * (in red) indicates required fields

**Comment by cwant** [comment]
@seanluyk I don't have admin rights on ERA -- would you mind taking a screenshot of the edit form just so I can see what you had in mind?

**Comment by seanluyk** [comment]
Here you go @cwant!:
![image](https://cloud.githubusercontent.com/assets/14880206/24930382/886efe28-1ec6-11e7-9c7b-86a3af06881c.png)

P.S. You're also able to see this if you log in to ERA and upload a file
